# Description table for brain anatomy GLB bases (filename without .glb and without .l/.r).
$descriptions = @{
  # --- Cerebral cortex ---
  'Frontal_Inferior frontal sulcus' = 'The inferior frontal sulcus separates the middle frontal gyrus from the inferior frontal gyrus on the lateral frontal convexity. It is a major landmark for localising the inferior frontal language and motor association territories and for navigating frontal approaches near Broca''s region.'
  'Frontal_Lat_Fis-ant-Horizont' = 'The anterior horizontal ramus of the lateral (Sylvian) fissure is a short frontal branch that helps define the triangular and orbital parts of the inferior frontal gyrus. It is a key sulcal landmark in language-network mapping and opercular anatomy.'
  'Frontal_Lat_Fis-ant-Vertical' = 'The anterior vertical (ascending) ramus of the lateral fissure bounds the triangular part of the inferior frontal gyrus and contributes to the classic M shape of Broca''s region. It separates pars triangularis from pars opercularis and guides cortical language localisation.'
  'Frontal_Middle frontal gyrus' = 'The middle frontal gyrus lies between the superior and inferior frontal sulci and hosts premotor, frontal eye-field, and dorsolateral prefrontal territories. It supports working memory, attentional control, and voluntary eye movements, and is frequently involved in executive-function networks.'
  'Frontal_Olfactory sulcus' = 'The olfactory sulcus runs on the ventral frontal lobe parallel to the gyrus rectus and lodges the olfactory tract. It is an important basal frontal landmark relating orbitofrontal cortex to olfactory pathways and medial orbital gyri.'
  'Frontal_Opercular part of inferior frontal gyrus' = 'Pars opercularis of the inferior frontal gyrus forms the posterior limb of Broca''s region (roughly Brodmann area 44). It participates in speech production, phonological processing, and orofacial motor planning, and abuts the precentral gyrus posteriorly.'
  'Frontal_Orbital gyri (Frontomarginal gyrus and sulcus)' = 'The frontomarginal gyrus and sulcus occupy the frontal pole''s ventral-lateral margin. They belong to orbitofrontal / frontopolar association cortex involved in value-based decision making, social cognition, and integrating sensory cues with goal-directed behaviour.'
  'Frontal_Orbital gyri' = 'The orbital gyri form the corrugated ventral surface of the frontal lobe above the orbit. Orbitofrontal cortex evaluates reward, punishment, and olfactory-gustatory information and is clinically relevant in personality change after basal frontal injury.'
  'Frontal_Orbital part of inferior frontal gyrus' = 'Pars orbitalis is the most anterior division of the inferior frontal gyrus (roughly Brodmann area 47/12). It contributes to semantic control, lexical retrieval, and affective-linguistic integration within the broader Broca network.'
  'Frontal_Orbital sulci (H-shaped orbital sulci)' = 'The H-shaped orbital sulci pattern the orbital surface into medial, anterior, posterior, and lateral orbital gyri. They provide reliable landmarks for orbitofrontal parcellation in imaging and surgical planning along the basal frontal lobe.'
  'Frontal_Orbital sulci (Lateral Orbital sulcus)' = 'The lateral orbital sulcus helps separate lateral orbital cortex from neighbouring frontal opercular and frontomarginal territories. It is part of the ventral frontal sulcal map used to orient within orbitofrontal association cortex.'
  'Frontal_Paracentral gyrus and sulcus' = 'The paracentral lobule straddles the medial hemispheric surface around the end of the central sulcus, combining medial precentral (motor) and postcentral (sensory) cortices for the lower limb and perineum. The paracentral sulcus helps bound this medial sensorimotor territory.'
  'Frontal_Paracentral sulcus' = 'The paracentral sulcus is a medial frontal sulcus that helps demarcate the paracentral lobule from more anterior medial frontal cortex. It is a useful midline landmark when relating medial motor cortex to the cingulate and superior frontal gyrus.'
  'Frontal_Precentral gyrus' = 'The precentral gyrus is the primary motor cortex (Brodmann area 4), organised somatotopically along the motor homunculus. It issues corticospinal and corticonuclear fibres that drive voluntary movement of the contralateral body and face.'
  'Frontal_Precentral sulcus (inferior part)' = 'The inferior precentral sulcus separates premotor cortex from the precentral gyrus in the lower frontal convexity and helps locate the face-hand motor representations. It is a critical landmark for rolandic and opercular surgical approaches.'
  'Frontal_Precentral sulcus (Superior part)' = 'The superior precentral sulcus bounds the upper motor and premotor strip near the hand knob and dorsal premotor cortex. Together with the superior frontal sulcus it frames dorsolateral premotor and frontal eye-field neighbourhoods.'
  'Frontal_Straight gyrus (Gyrus rectus)' = 'The gyrus rectus (straight gyrus) is the medial-most strip of orbitofrontal cortex, flanking the olfactory sulcus. It participates in olfactory and value-related processing and is a classic landmark on the basal frontal surface.'
  'Frontal_Superior frontal gyrus' = 'The superior frontal gyrus occupies the dorsomedial frontal lobe and contains supplementary motor, pre-SMA, and prefrontal territories. It supports motor initiation, cognitive control, and aspects of working memory and social cognition.'
  'Frontal_Superior frontal sulcus' = 'The superior frontal sulcus divides the superior from the middle frontal gyrus and is a major anteroposterior landmark of the dorsolateral frontal lobe. Its posterior end helps localise the frontal eye field and dorsal premotor cortex.'
  'Frontal_Transverse frontopolar gyrus and sulcus' = 'Transverse frontopolar gyrus and sulcus mark the frontal pole''s transition between lateral and orbital surfaces. Frontopolar cortex (roughly area 10) is implicated in multitasking, prospective memory, and the highest levels of cognitive branching.'
  'Frontal_Triangular part of inferior frontal gyrus' = 'Pars triangularis occupies the middle portion of the inferior frontal gyrus (roughly Brodmann area 45) between the anterior rami of the Sylvian fissure. It is central to language production, semantic processing, and syntactic computation in the dominant hemisphere.'
  'Insula_Insula (Subcentral gyrus and ant. and post. sulci)' = 'This insular parcel includes the subcentral gyrus and the anterior and posterior sulci that frame the inferior central region as it tunnels into the Sylvian fissure. Insular cortex integrates interoception, pain, taste, autonomic tone, and speech-motor coordination.'
  'Limbic_Cingulate gyrus (Posteroventral part)' = 'The posteroventral cingulate belongs to the posterior cingulate / retrosplenial neighbourhood on the medial surface. It participates in autobiographical memory, spatial orientation, and the default-mode network, linking limbic and parietal association systems.'
  'Limbic_Cingulate gyrus and sulcus (Middle anterior part)' = 'The mid-anterior cingulate gyrus and sulcus overlie dorsal anterior cingulate cortex involved in conflict monitoring, motivation, and pain affect. This region is a hub of the salience network and a common target in psychiatric neuromodulation research.'
  'Limbic_Cingulate gyrus and sulcus (Middle posterior part)' = 'The mid-posterior cingulate segment bridges anterior executive cingulate cortex with posterior mnemonic cingulate territories. It contributes to attentional shifting, self-referential processing, and cortico-limbic integration along the medial wall.'
  'Limbic_Cingulate gyrus and sulcus (Posterior dorsal part)' = 'The posterior dorsal cingulate gyrus and sulcus sit near the splenium and precuneus interface. They support episodic memory retrieval, visuospatial processing, and dense connectivity within the default-mode network.'
  'Limbic_Cingulate sulcus (Marginal part)' = 'The marginal ramus of the cingulate sulcus ascends behind the paracentral lobule and is a reliable medial landmark separating parietal precuneus from the paracentral sensorimotor cortex. It is widely used in MRI-based medial lobe orientation.'
  'Limbic_Hippocampus' = 'The hippocampus is the archetypal limbic archicortical structure in the medial temporal lobe, essential for forming declarative memories and supporting spatial navigation. It is highly vulnerable in temporal-lobe epilepsy, Alzheimer disease, and hypoxic-ischaemic injury.'
  'Occipital_Calcarine sulcus' = 'The calcarine sulcus is the cardinal landmark of primary visual cortex (V1) on the medial occipital lobe. Upper and lower banks represent the contralateral lower and upper visual fields, making it fundamental to retinotopic organisation and visual-field defects.'
  'Occipital_Cuneus' = 'The cuneus lies above the calcarine sulcus on the medial occipital surface and contains upper-bank V1 plus adjacent early visual areas. It processes the contralateral lower visual field and feeds dorsal and ventral visual streams.'
  'Occipital_Inferior occipital gyrus and sulcus' = 'The inferior occipital gyrus and sulcus occupy the ventral-lateral occipital surface near the transition to the temporal lobe. They contribute to object and face-related visual processing within the ventral visual pathway.'
  'Occipital_Lateral occipital gyrus (Middle occipital gyrus)' = 'Lateral / middle occipital cortex belongs to extrastriate visual areas involved in form, motion, and object recognition. It links early visual cortex to parietal (dorsal) and temporal (ventral) association streams.'
  'Occipital_Lingual gyrus' = 'The lingual gyrus lies below the calcarine sulcus and contains lower-bank primary visual cortex plus adjacent ventral visual areas. It processes the contralateral upper visual field and participates in word-form and complex visual analysis.'
  'Occipital_Lunate sulcus' = 'The lunate sulcus is an occipital sulcal landmark near the boundary of early visual cortex on the lateral-posterior surface. In humans it is variable but still useful for orienting extrastriate and polar occipital territories.'
  'Occipital_Occipital pole' = 'The occipital pole is the most posterior tip of the hemisphere and houses the macular representation of primary visual cortex. Cortical lesions here produce central (macular) visual-field defects with high impact on detailed vision.'
  'Occipital_Superior occipital gyri' = 'Superior occipital gyri form the dorsomedial and dorsolateral occipital convexity adjacent to the parieto-occipital junction. They contribute to early visual association processing and the dorsal stream''s spatial analysis.'
  'Occipital_Transverse occipital sulcus' = 'The transverse occipital sulcus helps parcel superior occipital cortex and often relates to the posterior end of the intraparietal sulcus. It is a useful landmark at the parieto-occipital transition for visual-spatial association cortex.'
  'Parietal_Angular gyrus' = 'The angular gyrus (inferior parietal lobule) sits at the junction of temporal, occipital, and parietal association cortex. It supports reading, calculation, semantic integration, and aspects of spatial attention; dominant lesions can produce alexia, agraphia, or Gerstmann-type deficits.'
  'Parietal_Intraparietal sulcus' = 'The intraparietal sulcus divides the superior and inferior parietal lobules and hosts frontoparietal circuits for spatial attention, saccades, and sensorimotor transformation. It is a core node of the dorsal attention network.'
  'Parietal_Postcentral gyrus' = 'The postcentral gyrus is primary somatosensory cortex (Brodmann areas 3, 1, 2), organised as a sensory homunculus. It receives thalamocortical tactile and proprioceptive input from the contralateral body and face.'
  'Parietal_Postcentral sulcus' = 'The postcentral sulcus separates primary somatosensory cortex from the superior parietal lobule and other posterior parietal areas. It marks the transition from unimodal sensory cortex to higher-order spatial and associative processing.'
  'Parietal_Precuneus' = 'The precuneus occupies the medial parietal lobe between the marginal cingulate ramus and the parieto-occipital sulcus. It is a major default-mode hub involved in mental imagery, episodic memory, and self-referential cognition.'
  'Parietal_Superior parietal lobule' = 'The superior parietal lobule lies above the intraparietal sulcus and mediates visuomotor coordination, spatial awareness, and reaching/grasping transformations. Lesions can cause optic ataxia or aspects of neglect and spatial disorientation.'
  'Parietal_Supramarginal gyrus' = 'The supramarginal gyrus forms the anterior inferior parietal lobule around the end of the Sylvian fissure. It contributes to phonological processing, tool use, and proprioceptive-spatial integration; dominant injury may impair language and praxis.'
  'Temporal_Inferior temporal gyrus' = 'The inferior temporal gyrus belongs to the ventral visual stream (what pathway) along the inferolateral temporal lobe. It supports object recognition, visual memory, and high-level feature binding en route to temporal pole and fusiform territories.'
  'Temporal_Inferior temporal sulcus' = 'The inferior temporal sulcus separates middle from inferior temporal gyri and participates in the lateral temporal association landscape. Nearby cortex contributes to visual motion, biological motion, and multimodal object processing.'
  'Temporal_Lateral occipitotemporal gyrus' = 'The lateral occipitotemporal (fusiform) gyrus on the ventral surface is famous for high-level visual categories, including faces (FFA) and word forms (VWFA). It is a key node of the ventral visual recognition stream.'
  'Temporal_Medial occipitotemporal gyrus (Parahippocampal)' = 'The parahippocampal gyrus flanks the hippocampus on the medial temporal lobe and encodes contextual and spatial scene information. It is central to memory encoding circuits and is often involved in mesial temporal epilepsy.'
  'Temporal_Middle temporal gyrus' = 'The middle temporal gyrus is a broad lateral temporal association region involved in language semantics, biological motion, and multimodal integration. In the dominant hemisphere it supports lexical-semantic networks linking auditory and visual meaning.'
  'Temporal_Occipitotemporal sulcus (Lateral part)' = 'The lateral occipitotemporal sulcus helps separate fusiform / occipitotemporal cortex from neighbouring inferior temporal territories on the ventral surface. It is an important landmark for ventral visual and memory-related cortex.'
  'Temporal_Superior temporal gyrus (Lateral part)' = 'The superior temporal gyrus contains primary and association auditory cortex and, in the dominant hemisphere, critical language comprehension territories (Wernicke neighbourhood). It processes sound, speech, and audiovisual integration along the Sylvian fissure.'
  'Temporal_Superior temporal sulcus' = 'The superior temporal sulcus is a deep lateral temporal sulcus implicated in social perception, biological motion, voice processing, and audiovisual speech. It is a major hub of the social brain and language-related association cortex.'
  'Temporal_Temporal plane' = 'The planum temporale is the superior temporal surface posterior to Heschl''s gyri within the Sylvian fossa. It is strongly linked to auditory association and language lateralisation and is often asymmetric between hemispheres.'
  'Temporal_Temporal pole' = 'The temporal pole is the anterior tip of the temporal lobe and a high-order association region for semantic memory, social-emotional meaning, and olfactory-limbic linkage. It is frequently involved in semantic dementia and temporal-lobe epilepsy networks.'
  'Temporal_Transverse temporal gyri' = 'The transverse temporal (Heschl''s) gyri on the superior temporal plane constitute primary auditory cortex. They contain tonotopic maps of sound frequency and are the first cortical station of the ascending auditory pathway.'

  # --- Cerebellum ---
  'Cerebellum_Anterior quadrangular lobule' = 'The anterior quadrangular lobule is the hemispheric part of the anterior cerebellar lobe continuous with the culmen. It receives spinocerebellar afferents and contributes to regulation of muscle tone, posture, and gait. Anterior-lobe disease classically produces a wide-based, unsteady gait.'
  'Cerebellum_Biventral lobule' = 'The biventral lobule is a two-bellied lobule on the inferior cerebellar hemisphere, continuous with the pyramis and sitting near the tonsil. It belongs to the posterior lobe and contributes to limb coordination.'
  'Cerebellum_Central lobule' = 'The central lobule sits immediately behind the lingula on the superior vermis and forms part of the anterior lobe. It receives spinocerebellar input related to trunk and proximal limb posture and expands laterally into the wing of the central lobule.'
  'Cerebellum_Culmen' = 'The culmen is the largest and most prominent lobule of the superior vermis, forming the peak of the anterior lobe. It is heavily involved in spinocerebellar control of posture and lower-limb coordination and is a key mid-sagittal MRI landmark.'
  'Cerebellum_Declive' = 'The declive is the first vermian lobule of the posterior lobe, lying immediately behind the primary fissure. It contributes to coordination of skilled movement and is continuous laterally with the superior semilunar / simple lobule.'
  'Cerebellum_Flocculus' = 'The flocculus is a small paired lobule of the flocculonodular lobe beside the middle cerebellar peduncle. It is a core vestibulocerebellar structure controlling gaze holding, smooth pursuit, and vestibulo-ocular reflexes.'
  'Cerebellum_Folium of vermis' = 'The folium of the vermis is a narrow transverse ridge of the posterior vermis, continuous laterally with the superior semilunar lobule. It participates in oculomotor and cognitive-affective cerebellar networks of the posterior lobe.'
  'Cerebellum_Gracile lobule' = 'The gracile lobule is a slender hemispheric lobule of the inferior cerebellum associated with the pyramis. It participates in posterior-lobe coordination of distal limb movement between the inferior semilunar and biventral lobules.'
  'Cerebellum_Inferior semilunar lobule' = 'The inferior semilunar lobule (crus II) occupies much of the inferior-posterior cerebellar hemisphere and is continuous with the tuber of the vermis. It supports skilled motor coordination and cerebellar cognitive networks.'
  'Cerebellum_Lingula of cerebellum' = 'The lingula is the most anterior lobule of the cerebellar vermis, a thin tongue-like leaflet resting against the superior medullary velum. It belongs to the paleocerebellum involved in postural tone.'
  'Cerebellum_Nodule of vermis' = 'The nodule is the most caudal vermian lobule and the midline component of the flocculonodular lobe. Together with the flocculus it is the primary cerebellar centre for vestibular reflexes, gaze stability, and balance.'
  'Cerebellum_Peduncle of flocculus' = 'The peduncle of the flocculus is the white-matter stalk attaching the flocculus to the inferior cerebellar surface near the middle cerebellar peduncle. It carries afferent and efferent fibres of flocculonodular vestibular circuits.'
  'Cerebellum_Posterior quadrangular lobule' = 'The posterior quadrangular (simple) lobule is the hemispheric continuation of the declive, lying just behind the primary fissure. It is neocerebellum participating in coordination of voluntary, skilled movement.'
  'Cerebellum_Pyramis of vermis' = 'The pyramis is a triangular lobule on the inferior vermis, continuous laterally with the biventral / gracile region. It receives substantial spinal and brainstem input related to limb and axial coordination.'
  'Cerebellum_Superior cerebellar peduncle' = 'The superior cerebellar peduncle is the primary cerebellar output pathway, carrying fibres from the deep cerebellar nuclei upward to the contralateral red nucleus and thalamus after midbrain decussation.'
  'Cerebellum_Superior semilunar lobule' = 'The superior semilunar lobule (crus I) is a large crescentic lobule on the superior-posterior cerebellar hemisphere, continuous with the folium. It is a major neocerebellar region linked via pontocerebellar fibres to cerebral association cortex.'
  'Cerebellum_Tonsil of cerebellum' = 'The cerebellar tonsil is a rounded lobule on the inferior medial hemisphere flanking the uvula beside the foramen magnum. Downward tonsillar herniation can compress the medulla and is the hallmark of Chiari I malformation.'
  'Cerebellum_Tuber of vermis' = 'The tuber of the vermis sits just below the folium on the posterior vermis and expands laterally into the inferior semilunar lobule. It contributes to eye-movement control and higher-order posterior-lobe functions.'
  'Cerebellum_Uvula of vermis' = 'The uvula is a rounded inferior vermian lobule hanging above the cerebellar tonsils and nodule. It is closely linked to vestibular and postural circuits of the vestibulocerebellum.'
  'Cerebellum_Wing of central lobule' = 'The wing of the central lobule is the paired hemispheric extension of the central lobule in the anterior lobe. It participates in circuits that regulate antigravity tone and gait just behind the midbrain.'

  # --- Cranial nerves ---
  'Abducens nerve (VI)' = 'Cranial nerve VI (abducens) exits the pontomedullary junction and innervates the lateral rectus muscle, abducting the eye. Lesions produce ipsilateral esotropia and horizontal diplopia that worsens on lateral gaze.'
  'Accessory nerve (XI)' = 'Cranial nerve XI (accessory) supplies sternocleidomastoid and trapezius for head rotation and shoulder elevation. It has cranial and spinal roots; injury causes weakness turning the head away from the lesion and shoulder shrug.'
  'Facial nerve (VII)' = 'Cranial nerve VII (facial) provides facial expression, taste from the anterior two-thirds of the tongue, and parasympathetic supply to lacrimal and salivary glands. Lower motor neuron lesions cause ipsilateral facial paralysis including the forehead.'
  'Glossopharyngeal nerve (IX)' = 'Cranial nerve IX (glossopharyngeal) carries taste from the posterior tongue, visceral afferents from the carotid sinus/body, and motor fibres to stylopharyngeus. It is essential for the afferent limb of the gag reflex.'
  'Hypoglossal nerve (XII)' = 'Cranial nerve XII (hypoglossal) is a pure motor nerve to the intrinsic and extrinsic tongue muscles. Unilateral lesions cause ipsilateral tongue weakness with deviation toward the weak side on protrusion.'
  'Oculomotor nerve (III)' = 'Cranial nerve III (oculomotor) innervates most extraocular muscles, levator palpebrae, and parasympathetic pupils. Complete palsy produces ptosis, a down-and-out eye, and a dilated pupil.'
  'Olfactory nerve (I)' = 'Cranial nerve I (olfactory) conveys smell from the olfactory epithelium via the olfactory bulb and tract to olfactory cortex. It is the only cranial nerve that does not relay through the thalamus before reaching cortex.'
  'Optic nerve (II)' = 'Cranial nerve II (optic) carries retinal ganglion axons from the eye to the optic chiasm and tract. It is a CNS tract myelinated by oligodendrocytes; lesions produce visual-field defects according to the site of injury.'
  'Trigeminal nerve (V)' = 'Cranial nerve V (trigeminal) provides facial sensation via V1-V3 and motor innervation to the muscles of mastication. It is the largest cranial nerve and a key landmark in middle cranial fossa and cavernous sinus anatomy.'
  'Trochlear nerve (IV)' = 'Cranial nerve IV (trochlear) is the only cranial nerve to decussate fully and exit dorsally; it innervates the superior oblique. Palsy causes vertical diplopia, especially on downgaze and toward the nose.'
  'Vagus nerve (X)' = 'Cranial nerve X (vagus) is the major parasympathetic nerve to the thorax and abdomen and supplies laryngeal and pharyngeal muscles. It is critical for voice, swallowing, and autonomic control of heart, lungs, and gut.'
  'Vestibulocochlear nerve (VIII)' = 'Cranial nerve VIII (vestibulocochlear) carries hearing and balance information from the inner ear to the brainstem. Lesions produce hearing loss, tinnitus, vertigo, and imbalance, often with CPA tumour syndromes.'

  # --- Subcortical ---
  'BasalForebrain_Amygdaloid body' = 'The amygdaloid body is a deep temporal nuclear complex central to fear, emotion, and affective memory. It links olfactory, limbic, and autonomic circuits and is frequently involved in mesial temporal epilepsy.'
  'BasalForebrain_Septal nuclei' = 'The septal nuclei sit in the medial basal forebrain near the septum pellucidum and are a major cholinergic / limbic relay. They project to the hippocampus via the fornix and participate in memory and reward-related behaviour.'
  'Diencephalon_Habenula' = 'The habenula is a small epithalamic nucleus involved in aversion, negative reward prediction, and monoaminergic modulation. It links basal forebrain and limbic input to midbrain dopamine and serotonin systems.'
  'Diencephalon_Hypothalamus' = 'The hypothalamus is the master homeostatic centre controlling autonomic tone, endocrine output via the pituitary, temperature, hunger, thirst, and circadian rhythms. Tiny lesions can have outsized systemic effects.'
  'Diencephalon_Lateral geniculate body' = 'The lateral geniculate nucleus is the thalamic relay of the visual pathway, receiving optic tract input and projecting via optic radiations to primary visual cortex. It preserves retinotopic organisation of the contralateral visual field.'
  'Diencephalon_Mamillary body' = 'The mammillary bodies are hypothalamic nuclei on the ventral diencephalon that receive fornix input and project via the mammillothalamic tract to the anterior thalamus. They are critical nodes of the Papez memory circuit and are damaged in Wernicke-Korsakoff syndrome.'
  'Diencephalon_Medial geniculate body' = 'The medial geniculate nucleus is the thalamic auditory relay, receiving brainstem auditory input and projecting to Heschl''s gyri. It is essential for conscious hearing and auditory localisation.'
  'Diencephalon_Optic chiasm' = 'The optic chiasm is the midline crossing of nasal retinal fibres from each optic nerve. Compression here (classically by pituitary masses) produces bitemporal hemianopia.'
  'Diencephalon_Optic tract' = 'The optic tract carries post-chiasmatic visual fibres to the lateral geniculate nucleus. Unilateral lesions cause incongruous homonymous hemianopia of the contralateral visual field.'
  'Diencephalon_Posterior commissure' = 'The posterior commissure crosses the midline at the junction of the third ventricle and cerebral aqueduct and is involved in coordinating vertical gaze and pupillary light reflexes (pretectal circuits).'
  'Diencephalon_Stria medullaris thalami' = 'The stria medullaris thalami is a fibre bundle along the dorsomedial thalamus carrying basal forebrain and septal fibres to the habenula. It is a key white-matter landmark of the epithalamic corridor.'
  'Diencephalon_Thalamus' = 'The thalamus is the principal diencephalic relay and gating station between subcortical systems and cerebral cortex. Specific nuclei serve sensory, motor, limbic, and association functions; bilateral injury can cause coma or severe cognitive impairment.'
  'Diencephalon_Third ventricle' = 'The third ventricle is the midline CSF cavity between the thalami, continuous with the lateral ventricles via the foramina of Monro and with the aqueduct caudally. It is a critical landmark for deep endoscopic and stereotactic approaches.'
  'Striatum_Caudate nucleus' = 'The caudate nucleus is a C-shaped striatal mass forming the lateral wall of the lateral ventricle. Together with the putamen it is the main basal-ganglia input station for goal-directed action selection and habit learning.'
  'Striatum_Globus pallidus' = 'The globus pallidus is the medial lentiform output nucleus of the basal ganglia, divided into external and internal segments. GPi is a principal inhibitory output to thalamus and a classic target for DBS in movement disorders.'
  'Striatum_Lentiform nucleus' = 'The lentiform nucleus comprises putamen and globus pallidus as a wedge-shaped mass lateral to the internal capsule. It is a core basal-ganglia assembly for motor and cognitive loop processing.'
  'Striatum_Putamen' = 'The putamen is the lateral striatal nucleus and primary target of sensorimotor cortex. It is central to selecting and scaling voluntary movement; putaminal lesions cause contralateral rigidity, bradykinesia, or dystonia.'
  'Ventricles_WhiteMatter_Lateral ventricle' = 'The lateral ventricles are the paired CSF cavities within each cerebral hemisphere, with frontal, body, occipital, and temporal horns. They provide essential landmarks for hydrocephalus, mass effect, and neurosurgical navigation.'
  'Ventricles_WhiteMatter_Septum pellucidum' = 'The septum pellucidum is a thin midline membrane between the frontal horns of the lateral ventricles. Cavum septum pellucidum variants are common; absence may accompany developmental malformations.'
  'Ventricles_WhiteMatter_White matter of telencephalon' = 'Telencephalic white matter comprises the bulk of cortical association, commissural, and projection fibres within the cerebral hemispheres. It underpins distributed network connectivity; leukoaraiosis and demyelination disrupt these pathways.'

  # --- Commissures ---
  'Anterior commissure' = 'The anterior commissure is a compact midline white-matter bundle crossing in front of the columns of the fornix. It interconnects temporal and olfactory structures and is an important stereotactic landmark near the AC-PC line.'
  'Corpus callosum' = 'The corpus callosum is the largest cerebral commissure, linking homologous cortical areas across the midline through rostrum, genu, body, and splenium. Callosal lesions produce disconnection syndromes; it is a major target in epilepsy surgery.'
  'Fornix' = 'The fornix is the principal output pathway of the hippocampus, arching under the corpus callosum to the mammillary bodies and septal region. It is essential for episodic memory encoding and a key structure in the Papez circuit.'
  'Hippocampal commissure' = 'The hippocampal (psalterial) commissure interconnects the left and right hippocampal formations beneath the splenium / crus of the fornix. It contributes to bilateral temporal memory network communication.'

  # --- Vasculature: arteries ---
  'Artery_Anterior cerebral artery' = 'The anterior cerebral artery (ACA) arises from the internal carotid and supplies the medial frontal and parietal lobes, including the paracentral lobule. Occlusion classically causes contralateral lower-limb weakness and frontal behavioural signs.'
  'Artery_Anterior communicating artery' = 'The anterior communicating artery links the left and right ACAs and completes the anterior circle of Willis. It is a frequent site of saccular aneurysms presenting with subarachnoid haemorrhage.'
  'Artery_Anterior inferior cerebellar artery' = 'AICA arises from the basilar artery and supplies the anteroinferior cerebellum, middle cerebellar peduncle, and often the labyrinthine artery. Infarction can cause hearing loss, facial palsy, and lateral pontine signs.'
  'Artery_Anterior spinal artery' = 'The anterior spinal artery runs in the anterior median fissure of the spinal cord, usually formed by vertebral contributions. It supplies the anterior two-thirds of the cord; occlusion produces motor and spinothalamic deficits with relative dorsal-column sparing.'
  'Artery_Basilar artery' = 'The basilar artery is formed by vertebral confluence and ascends the ventral pons, giving pontine and cerebellar branches before terminating as the PCAs. Occlusion can cause locked-in syndrome or devastating brainstem infarction.'
  'Artery_External carotid artery' = 'The external carotid artery supplies face, scalp, meninges, and upper neck structures after branching from the common carotid. It is clinically important in extracranial-intracranial collateral pathways and head/neck embolisation.'
  'Artery_Insular branches of middle cerebral artery (M2)' = 'Insular (M2) branches of the MCA course over the insula within the Sylvian fissure before becoming opercular / cortical branches. They are key angiographic landmarks of the M2 segment and supply insular cortex.'
  'Artery_Insular branches of middle cerebral artery (M2-segment)' = 'Insular M2-segment branches of the MCA traverse the insular surface in the Sylvian cistern. They mark the transition from M1 stem to opercular and cortical MCA distribution.'
  'Artery_Internal carotid artery' = 'The internal carotid artery ascends to the skull base and cavernous sinus, then divides into MCA and ACA. It is the main anterior circulation feeder; stenosis or occlusion is a leading cause of ischaemic stroke.'
  'Artery_Lateral pontine branches of basilar artery' = 'Lateral pontine perforators from the basilar artery supply lateral tegmental and middle-peduncle territories of the pons. Occlusion contributes to lateral pontine syndromes with cranial-nerve and long-tract findings.'
  'Artery_Left common carotid artery' = 'The left common carotid artery usually arises directly from the aortic arch and bifurcates into internal and external carotids. It is a primary conduit of left hemispheric and cranial blood flow.'
  'Artery_Medial pontine branches of basilar artery' = 'Medial pontine perforating branches of the basilar artery supply paramedian pontine base and tegmentum. Occlusion produces classic lacunar pontine syndromes such as pure motor hemiparesis or dysarthria-clumsy hand.'
  'Artery_Middle cerebral artery (M1-segment)' = 'The M1 segment of the MCA runs in the Sylvian fissure from the ICA bifurcation to the limen insulae, giving lenticulostriate perforators. M1 occlusion causes large hemispheric stroke with dense hemiparesis and aphasia or neglect.'
  'Artery_Middle cerebral artery (M3 segment)' = 'M3 opercular branches of the MCA exit the Sylvian fissure onto the frontal, parietal, and temporal opercula. They supply peri-Sylvian language and sensorimotor cortices.'
  'Artery_Middle cerebral artery (M3-segment)' = 'The M3 segment comprises opercular MCA branches ascending from the Sylvian fissure onto the cortical surface. Distal emboli here produce more restricted cortical infarcts than M1 stem occlusion.'
  'Artery_Orbitofrontal branches of anterior cerebral artery' = 'Orbitofrontal ACA branches supply orbital and medial frontal cortex. They contribute to frontal behavioural and olfactory-related territories of the ACA distribution.'
  'Artery_Parietal branches of middle cerebral artery' = 'Parietal MCA branches supply superior and inferior parietal association cortex. Infarcts here can cause neglect, apraxia, or Gerstmann-type deficits depending on hemisphere and exact territory.'
  'Artery_Posterior cerebral artery' = 'The posterior cerebral artery supplies the occipital lobe, medial temporal lobe, and parts of the thalamus via thalamoperforators. Occipital PCA stroke classically produces contralateral hemianopia.'
  'Artery_Posterior communicating artery' = 'The posterior communicating artery links the ICA to the PCA and completes the posterior circle of Willis. It is a common aneurysm site and an important collateral pathway between anterior and posterior circulations.'
  'Artery_Posterior inferior cerebellar artery' = 'PICA usually arises from the vertebral artery and supplies the inferior cerebellum and lateral medulla. Occlusion can cause Wallenberg (lateral medullary) syndrome and inferior cerebellar infarction.'
  'Artery_Right common carotid artery' = 'The right common carotid artery typically arises from the brachiocephalic trunk and bifurcates into internal and external carotids. It supplies the right anterior cranial circulation and extracranial head/neck branches.'
  'Artery_Superior cerebellar artery' = 'The superior cerebellar artery arises near the basilar tip and supplies the superior cerebellum and midbrain tectum. SCA infarction causes ipsilateral ataxia and may involve the superior cerebellar peduncle.'
  'Artery_Temporal branches of middle cerebral artery' = 'Temporal MCA branches supply lateral temporal cortex involved in auditory and language association. Dominant-hemisphere infarcts can impair comprehension and lexical-semantic processing.'
  'Artery_Vertebral artery' = 'The vertebral arteries ascend in the cervical transverse foramina, enter the skull via the foramen magnum, and unite to form the basilar artery. They supply the medulla, cerebellum (via PICA), and contribute to the anterior spinal artery.'

  # --- Vasculature: veins / sinuses ---
  'Vein_Anterior intercavernous sinus' = 'The anterior intercavernous sinus connects the two cavernous sinuses across the midline in front of the pituitary. It is part of the circular sinus network relevant to transsphenoidal and cavernous approaches.'
  'Vein_Cavernous sinus' = 'The cavernous sinus is a paired dural venous sinus flanking the sella, containing ICA and cranial nerves III, IV, V1/V2, and VI. Thrombosis or fistula here produces ophthalmoplegia, chemosis, and orbital congestion.'
  'Vein_Inferior petrosal sinus' = 'The inferior petrosal sinus drains the cavernous sinus to the jugular bulb along the petro-occipital fissure. It is sampled in inferior petrosal sinus sampling for Cushing disease workups.'
  'Vein_Inferior sagittal sinus' = 'The inferior sagittal sinus runs in the free edge of the falx and drains into the straight sinus with the vein of Galen. It receives medial hemispheric cortical venous drainage.'
  'Vein_Internal jugular vein' = 'The internal jugular vein is the main extracranial continuation of the sigmoid sinus at the jugular foramen. It returns most intracranial venous blood to the heart and is a key central venous access route.'
  'Vein_Occipital sinus' = 'The occipital sinus is a small midline dural sinus along the falx cerebelli, communicating with the torcula and marginal sinuses. It is variable but relevant in posterior fossa venous anatomy.'
  'Vein_Posterior intercavernous sinus' = 'The posterior intercavernous sinus links the cavernous sinuses behind the pituitary within the diaphragma sellae region. Together with the anterior intercavernous sinus it forms the circular sinus.'
  'Vein_Sigmoid sinus' = 'The sigmoid sinus is the S-shaped continuation of the transverse sinus down to the jugular bulb. It grooves the mastoid bone and is a critical landmark in lateral skull-base surgery.'
  'Vein_Straight sinus' = 'The straight sinus runs in the tentorial attachment of the falx, receiving the inferior sagittal sinus and vein of Galen before draining to the torcula. It is a major deep venous outflow pathway.'
  'Vein_Superior petrosal sinus' = 'The superior petrosal sinus runs along the petrous ridge from the cavernous sinus to the transverse-sigmoid junction. It is an important landmark in middle fossa and petrosectomy approaches.'
  'Vein_Superior sagittal sinus' = 'The superior sagittal sinus is the large midline dural sinus in the falx convexity, draining cortical veins toward the torcula. Thrombosis can cause raised ICP, headaches, and parasagittal venous infarcts or haemorrhage.'
  'Vein_Transverse sinus' = 'The transverse sinuses run laterally in the tentorium from the torcula to the sigmoid sinuses. Asymmetry is common; occlusion or thrombosis can impair hemispheric venous drainage.'
  'Vein_Vertebral vein' = 'The vertebral veins accompany the vertebral arteries through the cervical spine and help drain the craniovertebral venous plexus. They provide an extracranial collateral route for posterior fossa venous return.'
}

# Name-based fallbacks (brain_manifest.json "name" field), especially brainstem / deep nuclei.
$descriptionsByName = @{
  # Cranial nerves (manifest names)
  'Abducens nerve (VI)' = $descriptions['Abducens nerve (VI)']
  'Accessory nerve (XI)' = $descriptions['Accessory nerve (XI)']
  'Facial nerve (VII)' = $descriptions['Facial nerve (VII)']
  'Glossopharyngeal nerve (IX)' = $descriptions['Glossopharyngeal nerve (IX)']
  'Hypoglossal nerve (XII)' = $descriptions['Hypoglossal nerve (XII)']
  'Oculomotor nerve (III)' = $descriptions['Oculomotor nerve (III)']
  'Olfactory nerve (I)' = $descriptions['Olfactory nerve (I)']
  'Optic nerve (II)' = $descriptions['Optic nerve (II)']
  'Trigeminal nerve (V)' = $descriptions['Trigeminal nerve (V)']
  'Trochlear nerve (IV)' = $descriptions['Trochlear nerve (IV)']
  'Vagus nerve (X)' = $descriptions['Vagus nerve (X)']
  'Vestibulocochlear nerve (VIII)' = $descriptions['Vestibulocochlear nerve (VIII)']

  # Deep nuclei
  'Caudate nucleus' = $descriptions['Striatum_Caudate nucleus']
  'Globus pallidus' = $descriptions['Striatum_Globus pallidus']
  'Putamen' = $descriptions['Striatum_Putamen']
  'Subthalamic nucleus' = 'The subthalamic nucleus is a glutamatergic nucleus at the diencephalon-midbrain junction and a key node of the indirect pathway. STN deep-brain stimulation is a standard therapy for advanced Parkinson disease.'
  'Substantia nigra' = 'The substantia nigra occupies the midbrain tegmentum with compacta (dopaminergic nigrostriatal) and reticulata (GABAergic output) parts. Compacta loss is the hallmark of Parkinson disease.'
  'Locus coeruleus' = 'The locus coeruleus in the rostral pontine tegmentum is the brain''s principal noradrenergic nucleus, modulating arousal, attention, and stress responses across cortex and limbic circuits.'
  'Periaqueductal grey' = 'The periaqueductal grey surrounds the cerebral aqueduct and is a hub for pain modulation, defensive behaviour, and autonomic control via descending brainstem pathways.'

  # Commissures / named
  'Anterior commissure' = $descriptions['Anterior commissure']
  'Corpus callosum' = $descriptions['Corpus callosum']
  'Fornix' = $descriptions['Fornix']
  'Hippocampal commissure' = $descriptions['Hippocampal commissure']

  # Brainstem major regions
  'Medulla oblongata' = 'The medulla oblongata is the caudal brainstem, continuous with the spinal cord. It houses vital cardiovascular and respiratory centres, cranial-nerve nuclei, and ascending/descending tracts.'
  'Pons' = 'The pons is the middle brainstem segment linking midbrain and medulla, dominated by pontine nuclei and the massive middle cerebellar peduncle. It contains nuclei for CN V-VIII related circuits and corticopontocerebellar relays.'
  'Midbrain' = 'The midbrain (mesencephalon) contains the cerebral peduncles, tegmentum, and tectum. It is critical for eye movements, auditory/visual reflexes, and dopaminergic motor modulation.'
  'Fourth ventricle' = 'The fourth ventricle is the CSF cavity between cerebellum and brainstem, continuous with the aqueduct above and central canal / foramina below. It is a key landmark for posterior fossa surgery.'
  'Aqueduct of midbrain' = 'The cerebral aqueduct of Sylvius connects the third and fourth ventricles through the midbrain. Narrowing here is a classic cause of obstructive hydrocephalus.'
  'Red nucleus' = 'The red nucleus in the midbrain tegmentum participates in motor coordination via rubrospinal and cerebellar relays. It is a prominent landmark on axial midbrain imaging.'
  'Superior colliculus' = 'The superior colliculus is a midbrain tectal centre for visual orientation and gaze shifts. It integrates sensory maps to drive rapid eye and head movements.'
  'Inferior colliculus' = 'The inferior colliculus is a midbrain auditory hub receiving ascending brainstem auditory input before relay to the medial geniculate nucleus.'
  'Tectum of midbrain (colliculi)' = 'The midbrain tectum comprises the superior and inferior colliculi. It supports visual and auditory orienting reflexes at the roof of the midbrain.'
  'Base of cerebral peduncle' = 'The base of the cerebral peduncle carries corticospinal and corticobulbar fibres through the ventral midbrain. Lesions here produce contralateral hemiparesis, often with other midbrain signs.'
  'Pyramid of medulla oblongata' = 'The medullary pyramids carry corticospinal fibres on the ventral medulla before most fibres decussate at the pyramidal decussation. They are the classic landmark of the ventral medulla.'
  'Anterior corticospinal tract' = 'The anterior corticospinal tract carries uncrossed corticospinal fibres in the anterior spinal cord, mainly for axial and proximal motor control.'
  'Lateral corticospinal tract' = 'The lateral corticospinal tract is the main crossed voluntary motor pathway in the lateral spinal cord, enabling skilled distal limb movement.'
  'Cuneate fasciculus' = 'The cuneate fasciculus carries fine touch and proprioception from the upper body in the dorsal columns to the cuneate nucleus of the medulla.'
  'Gracile fasciculus' = 'The gracile fasciculus carries fine touch and proprioception from the lower body in the dorsal columns to the gracile nucleus of the medulla.'
  'Inferior cerebellar peduncle' = 'The inferior cerebellar peduncle is a major cerebellar input pathway carrying spinal, vestibular, and olivary information into the cerebellum for posture and coordination.'
  'Middle cerebellar peduncle' = 'The middle cerebellar peduncle carries pontocerebellar fibres into the cerebellar hemispheres and is the largest cerebellar peduncle, critical for skilled movement planning.'
  'Superior cerebellar peduncle' = 'The superior cerebellar peduncle is the primary cerebellar output pathway from deep nuclei to contralateral red nucleus and thalamus after midbrain decussation.'
  'Anterior cochlear nucleus' = 'The anterior (ventral) cochlear nucleus is the first brainstem relay of auditory nerve fibres and begins sound localisation and spectral processing.'
  'Posterior cochlear nucleus' = 'The posterior (dorsal) cochlear nucleus is an early auditory brainstem relay contributing to spectral and complex sound feature analysis.'
  'Vestibular nuclei' = 'The vestibular nuclei in the ponto-medullary tegmentum integrate labyrinthine input for balance, vestibulo-ocular reflexes, and postural control.'
  'Nucleus of solitary tract' = 'The nucleus of the solitary tract is the primary visceral sensory nucleus for taste and cardiorespiratory afferents carried by CN VII, IX, and X.'
  'Nucleus ambiguus' = 'Nucleus ambiguus provides special visceral efferent fibres to laryngeal and pharyngeal muscles via CN IX and X and is essential for swallowing and phonation.'
  'Posterior nucleus of vagus nerve' = 'The dorsal motor nucleus of the vagus provides parasympathetic preganglionic outflow to thoracic and abdominal viscera.'
  'Inferior salivatory nucleus' = 'The inferior salivatory nucleus provides parasympathetic supply to the parotid gland via the glossopharyngeal nerve.'
  'Superior salivatory nucleus' = 'The superior salivatory nucleus provides parasympathetic supply to submandibular, sublingual, and lacrimal glands via the facial nerve.'
  'Motor nucleus of facial nerve' = 'The facial motor nucleus in the pons innervates muscles of facial expression. Lower motor neuron lesions cause ipsilateral facial paralysis including the forehead.'
  'Nucleus of abducens nerve' = 'The abducens nucleus in the dorsal pons drives lateral rectus and, via internuclear neurons, coordinates horizontal conjugate gaze.'
  'Nucleus of accessory nerve' = 'The spinal accessory nucleus in the upper cervical cord innervates sternocleidomastoid and trapezius for head rotation and shoulder elevation.'
  'Nucleus of hypoglossal nerve' = 'The hypoglossal nucleus in the medulla innervates tongue muscles. Unilateral lesions cause ipsilateral tongue weakness.'
  'Nucleus of oculomotor nerve' = 'The oculomotor nuclear complex in the midbrain innervates most extraocular muscles and levator palpebrae, with nearby Edinger-Westphal parasympathetic cells for the pupil.'
  'Nucleus of trochlear nerve' = 'The trochlear nucleus in the midbrain innervates the contralateral superior oblique after its unique dorsal decussation.'
  'Accessory nucleus of oculomotor' = 'The accessory oculomotor (Edinger-Westphal) nucleus provides parasympathetic preganglionic fibres for pupillary constriction and accommodation.'

  # Manifest v2: cortex lobes + merged overview
  'Frontal lobe' = 'The frontal lobe is the largest cerebral lobe, spanning prefrontal, premotor, and primary motor cortices. It supports executive function, personality, language production, and voluntary movement.'
  'Insula' = 'The insula is buried in the Sylvian fissure and integrates interoception, taste, pain, autonomic tone, and speech-motor coordination. It is a hub linking limbic, sensory, and cognitive networks.'
  'Limbic lobe' = 'The limbic lobe on the medial hemispheric surface includes cingulate and related cortices that link emotion, memory, and motivation. It interfaces closely with hippocampus, amygdala, and prefrontal circuits.'
  'Occipital lobe' = 'The occipital lobe is the primary visual cortex and early visual association territory. It contains calcarine (V1) cortex and feeds dorsal and ventral visual streams for space and object processing.'
  'Parietal lobe' = 'The parietal lobe processes somatosensory input and builds spatial awareness, attention, and sensorimotor transformations. Dominant lesions can impair language-related calculation and praxis; non-dominant lesions often cause neglect.'
  'Temporal lobe' = 'The temporal lobe houses auditory cortex, language comprehension networks, and medial memory structures including the hippocampus. It is central to hearing, semantics, and episodic memory.'
  'Brainstem' = 'The brainstem comprises midbrain, pons, and medulla and is the conduit for ascending and descending tracts plus cranial-nerve nuclei. It houses vital respiratory, cardiovascular, and arousal centres.'
  'Cerebellum' = 'The cerebellum coordinates movement, posture, and motor learning via dense connections with brainstem and cerebral cortex. It also contributes to cognitive and affective networks of the cerebellar hemispheres and vermis.'
}
