/** Per-structure metadata keyed by GLB basename (no extension). */
export const BRAIN_STRUCTURE_META = {
  'Anterior commissure': { id: 'commissures_anterior_commissure_unpaired', category: 'commissures', subgroup: '', hemisphere: 'unpaired' },
  'BasalForebrain_Amygdaloid body.l': { id: 'subcortical_basalforebrain_amygdaloid_body_left', category: 'subcortical', subgroup: 'BasalForebrain', hemisphere: 'left' },
  'BasalForebrain_Amygdaloid body.r': { id: 'subcortical_basalforebrain_amygdaloid_body_right', category: 'subcortical', subgroup: 'BasalForebrain', hemisphere: 'right' },
  'BasalForebrain_Septal nuclei': { id: 'subcortical_basalforebrain_septal_nuclei_unpaired', category: 'subcortical', subgroup: 'BasalForebrain', hemisphere: 'unpaired' },
  'Brainstem': { id: 'overview_brainstem_unpaired', category: 'overview', subgroup: '', hemisphere: 'unpaired' },
  'Cerebellum': { id: 'overview_cerebellum_unpaired', category: 'overview', subgroup: '', hemisphere: 'unpaired' },
  'Corpus callosum': { id: 'commissures_corpus_callosum_unpaired', category: 'commissures', subgroup: '', hemisphere: 'unpaired' },
  'Diencephalon_Habenula': { id: 'subcortical_diencephalon_habenula_unpaired', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'unpaired' },
  'Diencephalon_Hypothalamus': { id: 'subcortical_diencephalon_hypothalamus_unpaired', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'unpaired' },
  'Diencephalon_Lateral geniculate body.l': { id: 'subcortical_diencephalon_lateral_geniculate_body_left', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'left' },
  'Diencephalon_Lateral geniculate body.r': { id: 'subcortical_diencephalon_lateral_geniculate_body_right', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'right' },
  'Diencephalon_Mamillary body.l': { id: 'subcortical_diencephalon_mamillary_body_left', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'left' },
  'Diencephalon_Mamillary body.r': { id: 'subcortical_diencephalon_mamillary_body_right', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'right' },
  'Diencephalon_Medial geniculate body.l': { id: 'subcortical_diencephalon_medial_geniculate_body_left', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'left' },
  'Diencephalon_Medial geniculate body.r': { id: 'subcortical_diencephalon_medial_geniculate_body_right', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'right' },
  'Diencephalon_Optic chiasm.l': { id: 'subcortical_diencephalon_optic_chiasm_left', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'left' },
  'Diencephalon_Optic chiasm.r': { id: 'subcortical_diencephalon_optic_chiasm_right', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'right' },
  'Diencephalon_Optic tract.l': { id: 'subcortical_diencephalon_optic_tract_left', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'left' },
  'Diencephalon_Optic tract.r': { id: 'subcortical_diencephalon_optic_tract_right', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'right' },
  'Diencephalon_Posterior commissure': { id: 'subcortical_diencephalon_posterior_commissure_unpaired', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'unpaired' },
  'Diencephalon_Stria medullaris thalami.l': { id: 'subcortical_diencephalon_stria_medullaris_thalami_left', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'left' },
  'Diencephalon_Stria medullaris thalami.r': { id: 'subcortical_diencephalon_stria_medullaris_thalami_right', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'right' },
  'Diencephalon_Thalamus.l': { id: 'subcortical_diencephalon_thalamus_left', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'left' },
  'Diencephalon_Thalamus.r': { id: 'subcortical_diencephalon_thalamus_right', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'right' },
  'Diencephalon_Third ventricle': { id: 'subcortical_diencephalon_third_ventricle_unpaired', category: 'subcortical', subgroup: 'Diencephalon', hemisphere: 'unpaired' },
  'Fornix.l': { id: 'commissures_fornix_left', category: 'commissures', subgroup: '', hemisphere: 'left' },
  'Fornix.r': { id: 'commissures_fornix_right', category: 'commissures', subgroup: '', hemisphere: 'right' },
  'Frontal_lobe.l': { id: 'cortex_frontal_lobe_left', category: 'cortex', subgroup: '', hemisphere: 'left' },
  'Frontal_lobe.r': { id: 'cortex_frontal_lobe_right', category: 'cortex', subgroup: '', hemisphere: 'right' },
  'Hippocampal commissure': { id: 'commissures_hippocampal_commissure_unpaired', category: 'commissures', subgroup: '', hemisphere: 'unpaired' },
  'Insula.l': { id: 'cortex_insula_left', category: 'cortex', subgroup: '', hemisphere: 'left' },
  'Insula.r': { id: 'cortex_insula_right', category: 'cortex', subgroup: '', hemisphere: 'right' },
  'Limbic_lobe.l': { id: 'cortex_limbic_lobe_left', category: 'cortex', subgroup: '', hemisphere: 'left' },
  'Limbic_lobe.r': { id: 'cortex_limbic_lobe_right', category: 'cortex', subgroup: '', hemisphere: 'right' },
  'Occipital_lobe.l': { id: 'cortex_occipital_lobe_left', category: 'cortex', subgroup: '', hemisphere: 'left' },
  'Occipital_lobe.r': { id: 'cortex_occipital_lobe_right', category: 'cortex', subgroup: '', hemisphere: 'right' },
  'Parietal_lobe.l': { id: 'cortex_parietal_lobe_left', category: 'cortex', subgroup: '', hemisphere: 'left' },
  'Parietal_lobe.r': { id: 'cortex_parietal_lobe_right', category: 'cortex', subgroup: '', hemisphere: 'right' },
  'Striatum_Caudate nucleus.l': { id: 'subcortical_striatum_caudate_nucleus_left', category: 'subcortical', subgroup: 'Striatum', hemisphere: 'left' },
  'Striatum_Caudate nucleus.r': { id: 'subcortical_striatum_caudate_nucleus_right', category: 'subcortical', subgroup: 'Striatum', hemisphere: 'right' },
  'Striatum_Globus pallidus.l': { id: 'subcortical_striatum_globus_pallidus_left', category: 'subcortical', subgroup: 'Striatum', hemisphere: 'left' },
  'Striatum_Globus pallidus.r': { id: 'subcortical_striatum_globus_pallidus_right', category: 'subcortical', subgroup: 'Striatum', hemisphere: 'right' },
  'Striatum_Lentiform nucleus.l': { id: 'subcortical_striatum_lentiform_nucleus_left', category: 'subcortical', subgroup: 'Striatum', hemisphere: 'left' },
  'Striatum_Lentiform nucleus.r': { id: 'subcortical_striatum_lentiform_nucleus_right', category: 'subcortical', subgroup: 'Striatum', hemisphere: 'right' },
  'Striatum_Putamen.l': { id: 'subcortical_striatum_putamen_left', category: 'subcortical', subgroup: 'Striatum', hemisphere: 'left' },
  'Striatum_Putamen.r': { id: 'subcortical_striatum_putamen_right', category: 'subcortical', subgroup: 'Striatum', hemisphere: 'right' },
  'Temporal_lobe.l': { id: 'cortex_temporal_lobe_left', category: 'cortex', subgroup: '', hemisphere: 'left' },
  'Temporal_lobe.r': { id: 'cortex_temporal_lobe_right', category: 'cortex', subgroup: '', hemisphere: 'right' },
  'Ventricles_WhiteMatter_Lateral ventricle.l': { id: 'subcortical_ventricles_whitematter_lateral_ventricle_left', category: 'subcortical', subgroup: 'Ventricles', hemisphere: 'left' },
  'Ventricles_WhiteMatter_Lateral ventricle.r': { id: 'subcortical_ventricles_whitematter_lateral_ventricle_right', category: 'subcortical', subgroup: 'Ventricles', hemisphere: 'right' },
  'Ventricles_WhiteMatter_Septum pellucidum': { id: 'subcortical_ventricles_whitematter_septum_pellucidum_unpaired', category: 'subcortical', subgroup: 'Ventricles', hemisphere: 'unpaired' },
  'Ventricles_WhiteMatter_White matter of telencephalon.l': { id: 'subcortical_ventricles_whitematter_white_matter_of_telencephalon_left', category: 'subcortical', subgroup: 'Ventricles', hemisphere: 'left' },
  'Ventricles_WhiteMatter_White matter of telencephalon.r': { id: 'subcortical_ventricles_whitematter_white_matter_of_telencephalon_right', category: 'subcortical', subgroup: 'Ventricles', hemisphere: 'right' },
  'Vestibulocochlear nerve (VIII).l': { id: 'cranial_nerves_vestibulocochlear_nerve_viii_left', category: 'cranial_nerves', subgroup: '', hemisphere: 'left' },
  'Vestibulocochlear nerve (VIII).r': { id: 'cranial_nerves_vestibulocochlear_nerve_viii_right', category: 'cranial_nerves', subgroup: '', hemisphere: 'right' },
};

