/**
 * Brain anatomy GLB filenames from public/brainstem_glb.
 * Generated from Documents/BrainAnatomy_GLB/brain_manifest.json (primary only).
 * Loaded at native atlas transforms - no per-structure repositioning.
 */
export const CEREBRAL_CORTEX_GLB_FILES = [
  'Anterior commissure.glb',
  'BasalForebrain_Amygdaloid body.l.glb',
  'BasalForebrain_Amygdaloid body.r.glb',
  'BasalForebrain_Septal nuclei.glb',
  'Brainstem.glb',
  'Cerebellum.glb',
  'Corpus callosum.glb',
  'Diencephalon_Habenula.glb',
  'Diencephalon_Hypothalamus.glb',
  'Diencephalon_Lateral geniculate body.l.glb',
  'Diencephalon_Lateral geniculate body.r.glb',
  'Diencephalon_Mamillary body.l.glb',
  'Diencephalon_Mamillary body.r.glb',
  'Diencephalon_Medial geniculate body.l.glb',
  'Diencephalon_Medial geniculate body.r.glb',
  'Diencephalon_Optic chiasm.l.glb',
  'Diencephalon_Optic chiasm.r.glb',
  'Diencephalon_Optic tract.l.glb',
  'Diencephalon_Optic tract.r.glb',
  'Diencephalon_Posterior commissure.glb',
  'Diencephalon_Stria medullaris thalami.l.glb',
  'Diencephalon_Stria medullaris thalami.r.glb',
  'Diencephalon_Thalamus.l.glb',
  'Diencephalon_Thalamus.r.glb',
  'Diencephalon_Third ventricle.glb',
  'Fornix.l.glb',
  'Fornix.r.glb',
  'Frontal_lobe.l.glb',
  'Frontal_lobe.r.glb',
  'Hippocampal commissure.glb',
  'Insula.l.glb',
  'Insula.r.glb',
  'Limbic_lobe.l.glb',
  'Limbic_lobe.r.glb',
  'Occipital_lobe.l.glb',
  'Occipital_lobe.r.glb',
  'Parietal_lobe.l.glb',
  'Parietal_lobe.r.glb',
  'Striatum_Caudate nucleus.l.glb',
  'Striatum_Caudate nucleus.r.glb',
  'Striatum_Globus pallidus.l.glb',
  'Striatum_Globus pallidus.r.glb',
  'Striatum_Lentiform nucleus.l.glb',
  'Striatum_Lentiform nucleus.r.glb',
  'Striatum_Putamen.l.glb',
  'Striatum_Putamen.r.glb',
  'Temporal_lobe.l.glb',
  'Temporal_lobe.r.glb',
  'Ventricles_WhiteMatter_Lateral ventricle.l.glb',
  'Ventricles_WhiteMatter_Lateral ventricle.r.glb',
  'Ventricles_WhiteMatter_Septum pellucidum.glb',
  'Ventricles_WhiteMatter_White matter of telencephalon.l.glb',
  'Ventricles_WhiteMatter_White matter of telencephalon.r.glb',
  'Vestibulocochlear nerve (VIII).l.glb',
  'Vestibulocochlear nerve (VIII).r.glb',
];

