// Keys match exported .glb filenames (without extension).
// Generated from brain_manifest.json primary structures.
// Lookup: cerebralCortexStructures[clickedObject.name]

const cerebralCortexStructures = {
  'Anterior commissure': {
    title: 'ANTERIOR COMMISSURE',
    description:
      'The anterior commissure is a compact bundle of white-matter fibres crossing the midline in the anterior wall of the third ventricle, just in front of the columns of the fornix. It interconnects the temporal lobes (including olfactory and amygdaloid-related pathways) and smaller neocortical territories, forming a second major telencephalic commissure after the corpus callosum.\n\nTogether with the posterior commissure and callosal fibres, it contributes to bilateral coordination of olfactory, limbic, and some auditory-temporal processing. In stereotactic neurosurgery and imaging, the anterior commissure (AC) and posterior commissure (PC) define the classic AC-PC line used to localise deep nuclei.\n\nSmall though it is, the AC is a reliable midline landmark on axial and sagittal MRI. Lesions are uncommon in isolation but may accompany anterior third-ventricular or basal forebrain pathology. Identifying the AC helps orient the viewer to the lamina terminalis region and the anterior columns of the fornix.',
  },
  'BasalForebrain_Amygdaloid body.l': {
    title: 'AMYGDALOID BODY (LEFT)',
    description:
      'The amygdaloid body (amygdala) is an almond-shaped nuclear complex in the medial temporal lobe, just anterior to the hippocampus and deep to the uncus. It is a central node for emotional learning, especially fear conditioning, and for attaching affective value to sensory stimuli. Major divisions include basolateral, corticomedial, and central nuclei with distinct connectivity.\n\nIt receives sensory and prefrontal input and projects to hypothalamus, brainstem autonomic centres, bed nucleus of the stria terminalis, and widespread cortex. Through these paths it influences heart rate, respiration, stress hormones, and behavioural responses to threat. Olfactory pathways also relate closely to corticomedial amygdala.\n\nThe amygdala is frequently involved in mesial temporal epilepsy and can be a target of resective surgery. Psychiatric research links amygdalar circuits to anxiety, PTSD, and mood disorders. On coronal MRI it appears as grey matter anterior to the hippocampal head within the medial temporal lobe. This mesh shows the left-hemisphere component.',
  },
  'BasalForebrain_Amygdaloid body.r': {
    title: 'AMYGDALOID BODY (RIGHT)',
    description:
      'The amygdaloid body (amygdala) is an almond-shaped nuclear complex in the medial temporal lobe, just anterior to the hippocampus and deep to the uncus. It is a central node for emotional learning, especially fear conditioning, and for attaching affective value to sensory stimuli. Major divisions include basolateral, corticomedial, and central nuclei with distinct connectivity.\n\nIt receives sensory and prefrontal input and projects to hypothalamus, brainstem autonomic centres, bed nucleus of the stria terminalis, and widespread cortex. Through these paths it influences heart rate, respiration, stress hormones, and behavioural responses to threat. Olfactory pathways also relate closely to corticomedial amygdala.\n\nThe amygdala is frequently involved in mesial temporal epilepsy and can be a target of resective surgery. Psychiatric research links amygdalar circuits to anxiety, PTSD, and mood disorders. On coronal MRI it appears as grey matter anterior to the hippocampal head within the medial temporal lobe. This mesh shows the right-hemisphere component.',
  },
  'BasalForebrain_Septal nuclei': {
    title: 'SEPTAL NUCLEI',
    description:
      'The septal nuclei occupy the medial basal forebrain / septum verum region beneath the septum pellucidum and near the anterior commissure and columns of the fornix. They are an important cholinergic and limbic relay, interconnecting hippocampus (via fornix), hypothalamus, habenula (via stria medullaris), and prefrontal-cingulate networks.\n\nFunctionally the septum participates in memory, reward, and the generation of hippocampal theta rhythms that support encoding. It is part of the medial septal-diagonal band complex that provides major cholinergic innervation to the hippocampal formation.\n\nThough small, septal and basal forebrain cholinergic loss is relevant to Alzheimer disease and other memory disorders. Neighbouring structures include the nucleus accumbens and olfactory tubercle region. In the atlas the septal nuclei mark this medial basal forebrain limbic hub.',
  },
  'Brainstem': {
    title: 'BRAINSTEM',
    description:
      'The brainstem is the stalk connecting cerebrum and spinal cord and comprises three segments from rostral to caudal: midbrain, pons, and medulla oblongata. Through it run all ascending sensory and descending motor pathways between cortex and spinal cord, plus cerebellar peduncle connections.\n\nIt houses the nuclei of cranial nerves III-XII (with CN I-II related to forebrain pathways), the reticular formation for arousal and autonomic rhythm, and vital centres for breathing, heart rate, and blood pressure. The midbrain contains cerebral peduncles, red nucleus, substantia nigra, and colliculi; the pons carries massive pontocerebellar fibres; the medulla contains the pyramids and olive.\n\nBrainstem stroke, haemorrhage, compression, or demyelination can be life-threatening, producing crossed cranial-nerve and long-tract signs, locked-in syndrome, or coma. On imaging, the brainstem sits anterior to the cerebellum in the posterior fossa, with the fourth ventricle between them and the cerebral aqueduct traversing the midbrain.',
  },
  'Cerebellum': {
    title: 'CEREBELLUM',
    description:
      'The cerebellum occupies the posterior fossa beneath the tentorium and behind the brainstem. It has a midline vermis and two hemispheres, with an anterior lobe, posterior lobe, and flocculonodular lobe separated by deep fissures. Surface cortex is finely foliated; deep white matter contains the dentate, interposed, and fastigial nuclei.\n\nFunctionally it refines movement timing, coordination, and motor learning by comparing intended and actual motion. Vestibulocerebellum (flocculonodular) governs balance and eye movements; spinocerebellum (vermis/intermediate) regulates posture and gait; cerebrocerebellum (lateral hemispheres) supports skilled, planned limb movement and also cognitive-affective loops.\n\nCerebellar disease produces ipsilateral ataxia, dysmetria, intention tremor, nystagmus, and scanning speech rather than true weakness. Causes include infarct (SCA, AICA, PICA), haemorrhage, tumour, alcohol-related degeneration, and Chiari-related tonsillar descent. MRI shows the characteristic "tree of life" white-matter arborisation on sagittal views.',
  },
  'Corpus callosum': {
    title: 'CORPUS CALLOSUM',
    description:
      'The corpus callosum is the largest white-matter commissure of the brain, a broad midline plate linking homologous cortical regions of the left and right hemispheres. From anterior to posterior it is divided into rostrum, genu, body (trunk), and splenium, with a thin callosal isthmus near the junction of body and splenium.\n\nCallosal fibres enable interhemispheric transfer of sensory, motor, and cognitive information - for example linking language-dominant and non-dominant association cortex. The genu and forceps minor connect frontal lobes; the body links mainly parietal and frontal regions; the splenium and forceps major interconnect occipital and posterior temporal cortex.\n\nCallosotomy is sometimes used for intractable epilepsy to limit seizure spread. Congenital agenesis or acquired lesions can produce disconnection syndromes (for example alien-hand phenomena or left-hand anomia). On midline sagittal MRI the callosum is the bright arched band above the lateral ventricles; it is a fundamental landmark for almost every intracranial approach.',
  },
  'Diencephalon_Habenula': {
    title: 'HABENULA',
    description:
      'The habenula is a small paired epithalamic nucleus on the dorsomedial thalamus beside the third ventricle, near the pineal stalk. It receives input from basal forebrain and septal/limbic structures via the stria medullaris thalami and projects through the fasciculus retroflexus to midbrain monoaminergic centres (including interpeduncular nucleus and pathways influencing dopamine and serotonin neurons).\n\nFunctionally it encodes negative reward prediction, aversion, and disappointment - essentially signalling when outcomes are worse than expected - and thereby helps suppress futile or punished actions. It has become a research focus in depression, addiction, and mood regulation.\n\nThough tiny, the habenula is a meaningful landmark of the posterior third-ventricular roof region. Pathology is rarely isolated; nearby pineal or thalamic disease may involve it. In the interactive model it marks the epithalamic node linking limbic forebrain to brainstem neuromodulatory systems.',
  },
  'Diencephalon_Hypothalamus': {
    title: 'HYPOTHALAMUS',
    description:
      'The hypothalamus is a small but critical diencephalic region forming the floor and lower walls of the third ventricle, extending from the lamina terminalis and optic chiasm back to the mammillary bodies. Despite its size, it is the master coordinator of homeostasis: autonomic tone, endocrine control via the pituitary, temperature, hunger and thirst, sleep-wake and circadian rhythms, and aspects of reproductive and defensive behaviour.\n\nAnatomically it is organised into preoptic, anterior, tuberal, and posterior regions with medial and lateral zones. The paraventricular and supraoptic nuclei synthesise oxytocin and vasopressin for the posterior pituitary; releasing and inhibiting hormones regulate the anterior pituitary through the portal system. The hypothalamic-pituitary axis thus links neural and endocrine physiology.\n\nHypothalamic lesions - from tumours (craniopharyngioma, glioma), sarcoid, histiocytosis, or surgery - can cause diabetes insipidus, endocrine failure, obesity or cachexia, temperature dysregulation, and sleep-wake disturbance. On sagittal MRI it sits above the pituitary stalk between chiasm and mammillary bodies.',
  },
  'Diencephalon_Lateral geniculate body.l': {
    title: 'LATERAL GENICULATE BODY (LEFT)',
    description:
      'The lateral geniculate nucleus (LGN) is the thalamic relay of the visual pathway, a small layered nucleus on the posterior-inferior thalamus. It receives the optic tract (after partial decussation in the chiasm) and sends the optic radiations (geniculocalcarine tract) through parietal and temporal white matter to primary visual cortex in the occipital lobe.\n\nIts six principal layers segregate inputs from each eye and begin parallel processing of visual channels. Retinotopic organisation is preserved, so focal LGN lesions can produce characteristic incongruous or sectoranopic field defects. The LGN is thus the gateway from retina to conscious visual cortex.\n\nCompression or infarct in the posterior cerebral / anterior choroidal arterial territories may affect the LGN or nearby radiations. Identifying the LGN helps trace the entire visual pathway from eye to calcarine cortex in clinical neuroanatomy. This mesh shows the left-hemisphere component.',
  },
  'Diencephalon_Lateral geniculate body.r': {
    title: 'LATERAL GENICULATE BODY (RIGHT)',
    description:
      'The lateral geniculate nucleus (LGN) is the thalamic relay of the visual pathway, a small layered nucleus on the posterior-inferior thalamus. It receives the optic tract (after partial decussation in the chiasm) and sends the optic radiations (geniculocalcarine tract) through parietal and temporal white matter to primary visual cortex in the occipital lobe.\n\nIts six principal layers segregate inputs from each eye and begin parallel processing of visual channels. Retinotopic organisation is preserved, so focal LGN lesions can produce characteristic incongruous or sectoranopic field defects. The LGN is thus the gateway from retina to conscious visual cortex.\n\nCompression or infarct in the posterior cerebral / anterior choroidal arterial territories may affect the LGN or nearby radiations. Identifying the LGN helps trace the entire visual pathway from eye to calcarine cortex in clinical neuroanatomy. This mesh shows the right-hemisphere component.',
  },
  'Diencephalon_Mamillary body.l': {
    title: 'MAMILLARY BODY (LEFT)',
    description:
      'The mammillary (mamillary) bodies are a pair of small spherical nuclei on the posteroinferior hypothalamus, visible on the ventral brain surface between the cerebral peduncles and behind the pituitary stalk region. They receive dense hippocampal input through the fornix and project via the mammillothalamic tract to the anterior thalamic nuclei, continuing the Papez memory circuit toward cingulate cortex.\n\nThey are essential for consolidating episodic memory. In Wernicke-Korsakoff syndrome (thiamine deficiency), mammillary bodies are classically damaged, contributing to profound anterograde amnesia and confabulation. Trauma or tumours near the third-ventricular floor can likewise impair this node.\n\nOn midline sagittal MRI the mammillary bodies form the posterior hypothalamic "bumps" that help define the floor of the third ventricle. In this atlas, left and right mammillary parcels highlight their paired anatomy at the limbic-hypothalamic junction. This mesh shows the left-hemisphere component.',
  },
  'Diencephalon_Mamillary body.r': {
    title: 'MAMILLARY BODY (RIGHT)',
    description:
      'The mammillary (mamillary) bodies are a pair of small spherical nuclei on the posteroinferior hypothalamus, visible on the ventral brain surface between the cerebral peduncles and behind the pituitary stalk region. They receive dense hippocampal input through the fornix and project via the mammillothalamic tract to the anterior thalamic nuclei, continuing the Papez memory circuit toward cingulate cortex.\n\nThey are essential for consolidating episodic memory. In Wernicke-Korsakoff syndrome (thiamine deficiency), mammillary bodies are classically damaged, contributing to profound anterograde amnesia and confabulation. Trauma or tumours near the third-ventricular floor can likewise impair this node.\n\nOn midline sagittal MRI the mammillary bodies form the posterior hypothalamic "bumps" that help define the floor of the third ventricle. In this atlas, left and right mammillary parcels highlight their paired anatomy at the limbic-hypothalamic junction. This mesh shows the right-hemisphere component.',
  },
  'Diencephalon_Medial geniculate body.l': {
    title: 'MEDIAL GENICULATE BODY (LEFT)',
    description:
      'The medial geniculate nucleus (MGN) is the thalamic auditory relay, located on the posterior thalamus medial to the lateral geniculate. It receives ascending auditory information from the inferior colliculus via the brachium of the inferior colliculus and projects to primary auditory cortex in Heschl\'s gyri of the superior temporal plane.\n\nThrough the MGN, brainstem auditory computations about frequency, timing, and localisation are delivered to cortex for conscious hearing and further association. Different MGN subdivisions emphasise tonotopic core versus belt auditory processing.\n\nLesions of the MGN or its afferents can contribute to auditory processing disorders, though complete cortical deafness usually requires bilateral temporal damage. Together with the inferior colliculus and CN VIII, the MGN completes the classical ascending auditory pathway featured in this atlas. This mesh shows the left-hemisphere component.',
  },
  'Diencephalon_Medial geniculate body.r': {
    title: 'MEDIAL GENICULATE BODY (RIGHT)',
    description:
      'The medial geniculate nucleus (MGN) is the thalamic auditory relay, located on the posterior thalamus medial to the lateral geniculate. It receives ascending auditory information from the inferior colliculus via the brachium of the inferior colliculus and projects to primary auditory cortex in Heschl\'s gyri of the superior temporal plane.\n\nThrough the MGN, brainstem auditory computations about frequency, timing, and localisation are delivered to cortex for conscious hearing and further association. Different MGN subdivisions emphasise tonotopic core versus belt auditory processing.\n\nLesions of the MGN or its afferents can contribute to auditory processing disorders, though complete cortical deafness usually requires bilateral temporal damage. Together with the inferior colliculus and CN VIII, the MGN completes the classical ascending auditory pathway featured in this atlas. This mesh shows the right-hemisphere component.',
  },
  'Diencephalon_Optic chiasm.l': {
    title: 'OPTIC CHIASM (LEFT)',
    description:
      'The optic chiasm is the X-shaped crossing of optic nerve fibres on the ventral diencephalon, above the pituitary gland and anterior to the pituitary stalk, in the floor region of the third ventricle / suprasellar cistern. Nasal retinal fibres from each eye decussate here, while temporal fibres remain ipsilateral, so that each optic tract carries the contralateral visual hemifield.\n\nThis partial crossing is the anatomical basis of bitemporal hemianopia when the chiasm is compressed from below - classically by pituitary macroadenoma, craniopharyngioma, or other sellar/suprasellar masses. Superior compression or lateral involvement produces different field patterns.\n\nSurgically and radiologically the chiasm is a critical landmark of the anterior circle of Willis and lamina terminalis region. Identifying chiasm, optic nerves, and optic tracts is fundamental to localising lesions along the anterior visual pathway. This mesh shows the left-hemisphere component.',
  },
  'Diencephalon_Optic chiasm.r': {
    title: 'OPTIC CHIASM (RIGHT)',
    description:
      'The optic chiasm is the X-shaped crossing of optic nerve fibres on the ventral diencephalon, above the pituitary gland and anterior to the pituitary stalk, in the floor region of the third ventricle / suprasellar cistern. Nasal retinal fibres from each eye decussate here, while temporal fibres remain ipsilateral, so that each optic tract carries the contralateral visual hemifield.\n\nThis partial crossing is the anatomical basis of bitemporal hemianopia when the chiasm is compressed from below - classically by pituitary macroadenoma, craniopharyngioma, or other sellar/suprasellar masses. Superior compression or lateral involvement produces different field patterns.\n\nSurgically and radiologically the chiasm is a critical landmark of the anterior circle of Willis and lamina terminalis region. Identifying chiasm, optic nerves, and optic tracts is fundamental to localising lesions along the anterior visual pathway. This mesh shows the right-hemisphere component.',
  },
  'Diencephalon_Optic tract.l': {
    title: 'OPTIC TRACT (LEFT)',
    description:
      'The optic tract is the continuation of retinal ganglion-cell axons after the chiasm, sweeping around the cerebral peduncle toward the lateral geniculate nucleus. Each tract carries a complete contralateral visual hemifield representation (ipsilateral temporal and contralateral nasal retinal fibres that have joined at the chiasm).\n\nMost fibres synapse in the LGN; a minority reach the pretectum and superior colliculus for pupillary light reflexes and reflexive orientation. Optic-tract lesions produce incongruous homonymous hemianopia and may abolish the contralateral relative afferent pupillary pathway contribution.\n\nThe tract is supplied in part by anterior choroidal and posterior communicating arterial territories, so deep MCA/ICA-related infarcts can involve it with neighbouring capsule or thalamic structures. Tracing nerve â†’ chiasm â†’ tract â†’ LGN â†’ radiation â†’ cortex is the core method for diagnosing visual-pathway disease. This mesh shows the left-hemisphere component.',
  },
  'Diencephalon_Optic tract.r': {
    title: 'OPTIC TRACT (RIGHT)',
    description:
      'The optic tract is the continuation of retinal ganglion-cell axons after the chiasm, sweeping around the cerebral peduncle toward the lateral geniculate nucleus. Each tract carries a complete contralateral visual hemifield representation (ipsilateral temporal and contralateral nasal retinal fibres that have joined at the chiasm).\n\nMost fibres synapse in the LGN; a minority reach the pretectum and superior colliculus for pupillary light reflexes and reflexive orientation. Optic-tract lesions produce incongruous homonymous hemianopia and may abolish the contralateral relative afferent pupillary pathway contribution.\n\nThe tract is supplied in part by anterior choroidal and posterior communicating arterial territories, so deep MCA/ICA-related infarcts can involve it with neighbouring capsule or thalamic structures. Tracing nerve â†’ chiasm â†’ tract â†’ LGN â†’ radiation â†’ cortex is the core method for diagnosing visual-pathway disease. This mesh shows the right-hemisphere component.',
  },
  'Diencephalon_Posterior commissure': {
    title: 'POSTERIOR COMMISSURE',
    description:
      'The posterior commissure is a compact white-matter bundle crossing the midline at the junction of the third ventricle and the cerebral aqueduct, in the pretectal / pineal region just above the midbrain tegmentum. It interconnects pretectal and related midbrain nuclei involved in coordinated vertical gaze and the pupillary light reflex.\n\nClinically it is associated with the dorsal midbrain (Parinaud) syndrome when nearby tectal structures are compressed - for example by pineal tumours - producing upgaze palsy, light-near dissociation, and eyelid retraction. The posterior commissure itself is a key anatomical landmark for the entrance to the aqueduct.\n\nOn sagittal imaging it helps mark the posterior boundary of the third ventricle. Together with the anterior commissure it frames midline diencephalic reference points used in classical neuroanatomy and stereotactic orientation.',
  },
  'Diencephalon_Stria medullaris thalami.l': {
    title: 'STRIA MEDULLARIS THALAMI (LEFT)',
    description:
      'The stria medullaris thalami is a slender white-matter tract running along the dorsomedial surface of the thalamus toward the habenula. It carries fibres from septal nuclei, anterior basal forebrain, and related limbic regions into the epithalamic habenular complex, completing an important limbic pathway for aversion and monoaminergic modulation.\n\nTogether with the fasciculus retroflexus (habenulo-interpeduncular tract), it forms a corridor from forebrain emotion-motivation circuits down to midbrain neuromodulatory nuclei. The stria medullaris also helps define the lateral edge of the roof of the third ventricle on anatomical dissection.\n\nIt is a fine structure on imaging but a meaningful conceptual landmark linking septum, thalamus, and habenula. In this model it emphasises limbic wiring beyond the better-known fornix-mammillary path. This mesh shows the left-hemisphere component.',
  },
  'Diencephalon_Stria medullaris thalami.r': {
    title: 'STRIA MEDULLARIS THALAMI (RIGHT)',
    description:
      'The stria medullaris thalami is a slender white-matter tract running along the dorsomedial surface of the thalamus toward the habenula. It carries fibres from septal nuclei, anterior basal forebrain, and related limbic regions into the epithalamic habenular complex, completing an important limbic pathway for aversion and monoaminergic modulation.\n\nTogether with the fasciculus retroflexus (habenulo-interpeduncular tract), it forms a corridor from forebrain emotion-motivation circuits down to midbrain neuromodulatory nuclei. The stria medullaris also helps define the lateral edge of the roof of the third ventricle on anatomical dissection.\n\nIt is a fine structure on imaging but a meaningful conceptual landmark linking septum, thalamus, and habenula. In this model it emphasises limbic wiring beyond the better-known fornix-mammillary path. This mesh shows the right-hemisphere component.',
  },
  'Diencephalon_Thalamus.l': {
    title: 'THALAMUS (LEFT)',
    description:
      'The thalamus is a large paired diencephalic grey-matter mass sitting on either side of the third ventricle, above the hypothalamic sulcus and medial to the internal capsule. It is the principal relay and gating station between subcortical systems and cerebral cortex: virtually all sensory pathways (except olfaction) synapse in thalamic nuclei before reaching cortex, and many motor, limbic, and association loops do likewise.\n\nMajor nuclear groups include anterior (limbic), medial (including mediodorsal association), lateral and ventral (motor and sensory relays such as VPL/VPM, VL/VA), geniculate bodies (vision and hearing), and midline/intralaminar nuclei involved in arousal. The internal medullary lamina divides many of these groups.\n\nThalamic stroke can produce pure sensory loss, atypical pain syndromes (Dejerine-Roussy), aphasia-like deficits, neglect, or reduced arousal depending on the nucleus involved. The thalamus is also a target for deep-brain stimulation in tremor. On axial imaging it forms the ovoid grey masses flanking the third ventricle. This mesh shows the left-hemisphere component.',
  },
  'Diencephalon_Thalamus.r': {
    title: 'THALAMUS (RIGHT)',
    description:
      'The thalamus is a large paired diencephalic grey-matter mass sitting on either side of the third ventricle, above the hypothalamic sulcus and medial to the internal capsule. It is the principal relay and gating station between subcortical systems and cerebral cortex: virtually all sensory pathways (except olfaction) synapse in thalamic nuclei before reaching cortex, and many motor, limbic, and association loops do likewise.\n\nMajor nuclear groups include anterior (limbic), medial (including mediodorsal association), lateral and ventral (motor and sensory relays such as VPL/VPM, VL/VA), geniculate bodies (vision and hearing), and midline/intralaminar nuclei involved in arousal. The internal medullary lamina divides many of these groups.\n\nThalamic stroke can produce pure sensory loss, atypical pain syndromes (Dejerine-Roussy), aphasia-like deficits, neglect, or reduced arousal depending on the nucleus involved. The thalamus is also a target for deep-brain stimulation in tremor. On axial imaging it forms the ovoid grey masses flanking the third ventricle. This mesh shows the right-hemisphere component.',
  },
  'Diencephalon_Third ventricle': {
    title: 'THIRD VENTRICLE',
    description:
      'The third ventricle is the narrow midline CSF cavity of the diencephalon, lying between the two thalami and above the hypothalamus. It communicates with each lateral ventricle through the foramina of Monro (interventricular foramina) and drains caudally into the cerebral aqueduct of Sylvius toward the fourth ventricle.\n\nIts walls and floor are formed by critical grey-matter structures - thalamus, hypothalamus, and related landmarks including the optic chiasm, infundibulum, and mammillary bodies - so third-ventricular pathology quickly affects endocrine, visual, and memory systems. Choroid plexus in its roof contributes CSF.\n\nObstruction at the aqueduct or foramina of Monro produces obstructive hydrocephalus with elevated intracranial pressure. Colloid cysts near the foramen of Monro are a classic cause of intermittent obstruction. Endoscopic third ventriculostomy and other deep approaches use third-ventricular anatomy as a roadmap.',
  },
  'Fornix.l': {
    title: 'FORNIX (LEFT)',
    description:
      'The fornix is the principal efferent pathway of the hippocampal formation and a core white-matter tract of the limbic memory circuit. It arises as fimbria along the hippocampus, arches upward as the crus under the corpus callosum, joins briefly at the hippocampal commissure, then forms the body of the fornix before dividing into columns that descend toward the mammillary bodies and septal region.\n\nThrough this route, hippocampal output reaches the mammillary bodies (then anterior thalamus via the mammillothalamic tract) and basal forebrain, closing loops essential for episodic memory encoding and recall. The fornix therefore sits at the heart of the classic Papez circuit.\n\nInjury from trauma, surgery, infarct, or hydrocephalus-related stretch can cause severe anterograde amnesia. On coronal MRI the body of the fornix appears as paired or fused white-matter cords beneath the callosum; the columns are seen descending beside the foramen of Monro. Hemispheric fornix parcels in this atlas represent left and right components of this arching pathway. This mesh shows the left-hemisphere component.',
  },
  'Fornix.r': {
    title: 'FORNIX (RIGHT)',
    description:
      'The fornix is the principal efferent pathway of the hippocampal formation and a core white-matter tract of the limbic memory circuit. It arises as fimbria along the hippocampus, arches upward as the crus under the corpus callosum, joins briefly at the hippocampal commissure, then forms the body of the fornix before dividing into columns that descend toward the mammillary bodies and septal region.\n\nThrough this route, hippocampal output reaches the mammillary bodies (then anterior thalamus via the mammillothalamic tract) and basal forebrain, closing loops essential for episodic memory encoding and recall. The fornix therefore sits at the heart of the classic Papez circuit.\n\nInjury from trauma, surgery, infarct, or hydrocephalus-related stretch can cause severe anterograde amnesia. On coronal MRI the body of the fornix appears as paired or fused white-matter cords beneath the callosum; the columns are seen descending beside the foramen of Monro. Hemispheric fornix parcels in this atlas represent left and right components of this arching pathway. This mesh shows the right-hemisphere component.',
  },
  'Frontal_lobe.l': {
    title: 'FRONTAL LOBE (LEFT)',
    description:
      'The frontal lobe occupies the anterior third of each cerebral hemisphere, extending from the frontal pole back to the central sulcus and down to the lateral (Sylvian) fissure. It contains the primary motor cortex (precentral gyrus), premotor and supplementary motor areas, frontal eye fields, Broca\'s language region in the dominant hemisphere, and the large prefrontal association cortex.\n\nFunctionally it is the brain\'s executive centre: planning, working memory, decision making, social behaviour, personality, and voluntary movement all depend heavily on frontal networks. The orbitofrontal surface evaluates reward and emotion, while dorsolateral prefrontal cortex supports cognitive control.\n\nClinically, frontal lesions may produce hemiparesis, aphasia (dominant side), disinhibition, apathy, poor judgment, or gaze preference. Stroke in the anterior cerebral or middle cerebral artery territories commonly involves frontal cortex. On imaging, the frontal lobe is bounded posteriorly by the central sulcus and inferiorly by the Sylvian fissure. This mesh shows the left-hemisphere component.',
  },
  'Frontal_lobe.r': {
    title: 'FRONTAL LOBE (RIGHT)',
    description:
      'The frontal lobe occupies the anterior third of each cerebral hemisphere, extending from the frontal pole back to the central sulcus and down to the lateral (Sylvian) fissure. It contains the primary motor cortex (precentral gyrus), premotor and supplementary motor areas, frontal eye fields, Broca\'s language region in the dominant hemisphere, and the large prefrontal association cortex.\n\nFunctionally it is the brain\'s executive centre: planning, working memory, decision making, social behaviour, personality, and voluntary movement all depend heavily on frontal networks. The orbitofrontal surface evaluates reward and emotion, while dorsolateral prefrontal cortex supports cognitive control.\n\nClinically, frontal lesions may produce hemiparesis, aphasia (dominant side), disinhibition, apathy, poor judgment, or gaze preference. Stroke in the anterior cerebral or middle cerebral artery territories commonly involves frontal cortex. On imaging, the frontal lobe is bounded posteriorly by the central sulcus and inferiorly by the Sylvian fissure. This mesh shows the right-hemisphere component.',
  },
  'Hippocampal commissure': {
    title: 'HIPPOCAMPAL COMMISSURE',
    description:
      'The hippocampal commissure (commissure of the fornix / psalterium) is a thin sheet of crossing fibres linking the left and right hippocampal formations beneath the posterior body and crura of the fornix, near the splenium of the corpus callosum. It allows interhemispheric communication between mesial temporal memory networks.\n\nAlthough smaller and less often discussed than the corpus callosum or anterior commissure, it contributes to bilateral coordination of episodic memory processing and is part of the dorsal hippocampal commissural system described in classical anatomy. It lies in a surgically and radiologically delicate region where fornices, splenium, and ventricular atria converge.\n\nPathology here is usually secondary to nearby callosal, ventricular, or pineal-region disease rather than isolated commissural lesions. Recognising the hippocampal commissure helps explain how mesial temporal structures on each side remain functionally coupled within limbic circuitry.',
  },
  'Insula.l': {
    title: 'INSULA (LEFT)',
    description:
      'The insula (island of Reil) is a buried cortical lobe deep in the Sylvian fissure, covered by frontal, parietal, and temporal opercula. Short anterior and long posterior gyri are separated by the central sulcus of the insula. It receives visceral, gustatory, nociceptive, and interoceptive input and is a hub for awareness of internal body state.\n\nAnterior insula participates in salience, emotion, empathy, and autonomic regulation; posterior insula is more tightly linked to pain and somatosensory visceral representation. The insula also contributes to speech-motor planning and is near critical MCA (M2) arterial branches that course over its surface.\n\nInsular strokes may cause dysarthria, autonomic changes, gustatory disturbance, or language deficits when adjacent opercular cortex is involved. Surgically, the insula is approached through the Sylvian fissure with careful attention to lenticulostriate and M2 vessels. On coronal imaging it appears as cortex deep to the opercula facing the extreme capsule. This mesh shows the left-hemisphere component.',
  },
  'Insula.r': {
    title: 'INSULA (RIGHT)',
    description:
      'The insula (island of Reil) is a buried cortical lobe deep in the Sylvian fissure, covered by frontal, parietal, and temporal opercula. Short anterior and long posterior gyri are separated by the central sulcus of the insula. It receives visceral, gustatory, nociceptive, and interoceptive input and is a hub for awareness of internal body state.\n\nAnterior insula participates in salience, emotion, empathy, and autonomic regulation; posterior insula is more tightly linked to pain and somatosensory visceral representation. The insula also contributes to speech-motor planning and is near critical MCA (M2) arterial branches that course over its surface.\n\nInsular strokes may cause dysarthria, autonomic changes, gustatory disturbance, or language deficits when adjacent opercular cortex is involved. Surgically, the insula is approached through the Sylvian fissure with careful attention to lenticulostriate and M2 vessels. On coronal imaging it appears as cortex deep to the opercula facing the extreme capsule. This mesh shows the right-hemisphere component.',
  },
  'Limbic_lobe.l': {
    title: 'LIMBIC LOBE (LEFT)',
    description:
      'The limbic lobe is a medial hemispheric rim of cortex and related structures historically linked to emotion and memory. It includes the cingulate gyrus wrapping above the corpus callosum, plus closely related medial temporal and basal forebrain partners of the limbic network (hippocampus, parahippocampal cortex, amygdala, septal region).\n\nAnterior cingulate cortex participates in motivation, conflict monitoring, pain affect, and autonomic drive. Posterior cingulate and retrosplenial cortex are major default-mode hubs involved in autobiographical memory and spatial orientation. Through the Papez and related circuits, limbic cortex connects hippocampus, fornix, mammillary bodies, anterior thalamus, and cingulate cortex.\n\nLimbic dysfunction appears in epilepsy, Alzheimer disease, depression, anxiety disorders, and traumatic brain injury. Cingulate infarcts or tumours can alter affect, motivation, and autonomic control. On midline sagittal imaging, the cingulate gyrus is the curved cortical band above the callosal body. This mesh shows the left-hemisphere component.',
  },
  'Limbic_lobe.r': {
    title: 'LIMBIC LOBE (RIGHT)',
    description:
      'The limbic lobe is a medial hemispheric rim of cortex and related structures historically linked to emotion and memory. It includes the cingulate gyrus wrapping above the corpus callosum, plus closely related medial temporal and basal forebrain partners of the limbic network (hippocampus, parahippocampal cortex, amygdala, septal region).\n\nAnterior cingulate cortex participates in motivation, conflict monitoring, pain affect, and autonomic drive. Posterior cingulate and retrosplenial cortex are major default-mode hubs involved in autobiographical memory and spatial orientation. Through the Papez and related circuits, limbic cortex connects hippocampus, fornix, mammillary bodies, anterior thalamus, and cingulate cortex.\n\nLimbic dysfunction appears in epilepsy, Alzheimer disease, depression, anxiety disorders, and traumatic brain injury. Cingulate infarcts or tumours can alter affect, motivation, and autonomic control. On midline sagittal imaging, the cingulate gyrus is the curved cortical band above the callosal body. This mesh shows the right-hemisphere component.',
  },
  'Occipital_lobe.l': {
    title: 'OCCIPITAL LOBE (LEFT)',
    description:
      'The occipital lobe is the most posterior cerebral lobe and the seat of vision. Primary visual cortex (V1, Brodmann area 17) lines the calcarine sulcus on the medial surface; upper and lower banks represent the contralateral lower and upper visual fields, with the occipital pole representing central (macular) vision.\n\nSurrounding extrastriate areas (V2-V5 and association cortex) analyse colour, motion, form, and spatial relationships, feeding the dorsal ("where/how") stream toward parietal cortex and the ventral ("what") stream toward temporal cortex. The cuneus lies above the calcarine sulcus; the lingual gyrus lies below.\n\nOccipital stroke - classically posterior cerebral artery infarction - produces contralateral homonymous hemianopia, sometimes with macular sparing. Bilateral occipital injury can cause cortical blindness. Cortical visual disturbances (alexia without agraphia, visual agnosia) may follow lesions at occipito-temporal junctions. This mesh shows the left-hemisphere component.',
  },
  'Occipital_lobe.r': {
    title: 'OCCIPITAL LOBE (RIGHT)',
    description:
      'The occipital lobe is the most posterior cerebral lobe and the seat of vision. Primary visual cortex (V1, Brodmann area 17) lines the calcarine sulcus on the medial surface; upper and lower banks represent the contralateral lower and upper visual fields, with the occipital pole representing central (macular) vision.\n\nSurrounding extrastriate areas (V2-V5 and association cortex) analyse colour, motion, form, and spatial relationships, feeding the dorsal ("where/how") stream toward parietal cortex and the ventral ("what") stream toward temporal cortex. The cuneus lies above the calcarine sulcus; the lingual gyrus lies below.\n\nOccipital stroke - classically posterior cerebral artery infarction - produces contralateral homonymous hemianopia, sometimes with macular sparing. Bilateral occipital injury can cause cortical blindness. Cortical visual disturbances (alexia without agraphia, visual agnosia) may follow lesions at occipito-temporal junctions. This mesh shows the right-hemisphere component.',
  },
  'Parietal_lobe.l': {
    title: 'PARIETAL LOBE (LEFT)',
    description:
      'The parietal lobe lies behind the central sulcus, above the Sylvian fissure, and in front of the parieto-occipital and occipital territories. Its anterior bank is the postcentral gyrus - primary somatosensory cortex - organised as a sensory homunculus receiving touch, pain, temperature, and proprioception from the contralateral body.\n\nBehind this, superior and inferior parietal association cortex integrate spatial attention, body schema, visuomotor coordination, calculation, and aspects of language (especially in the dominant angular and supramarginal gyri). The intraparietal sulcus is a key landmark separating superior and inferior parietal lobules and hosts dorsal attention networks.\n\nDominant parietal injury can cause aphasia-related deficits, agraphia, acalculia, finger agnosia, or left-right confusion (Gerstmann features). Non-dominant lesions often produce hemispatial neglect, dressing apathy, or constructional impairment. MCA parietal branches are frequent stroke targets. This mesh shows the left-hemisphere component.',
  },
  'Parietal_lobe.r': {
    title: 'PARIETAL LOBE (RIGHT)',
    description:
      'The parietal lobe lies behind the central sulcus, above the Sylvian fissure, and in front of the parieto-occipital and occipital territories. Its anterior bank is the postcentral gyrus - primary somatosensory cortex - organised as a sensory homunculus receiving touch, pain, temperature, and proprioception from the contralateral body.\n\nBehind this, superior and inferior parietal association cortex integrate spatial attention, body schema, visuomotor coordination, calculation, and aspects of language (especially in the dominant angular and supramarginal gyri). The intraparietal sulcus is a key landmark separating superior and inferior parietal lobules and hosts dorsal attention networks.\n\nDominant parietal injury can cause aphasia-related deficits, agraphia, acalculia, finger agnosia, or left-right confusion (Gerstmann features). Non-dominant lesions often produce hemispatial neglect, dressing apathy, or constructional impairment. MCA parietal branches are frequent stroke targets. This mesh shows the right-hemisphere component.',
  },
  'Striatum_Caudate nucleus.l': {
    title: 'CAUDATE NUCLEUS (LEFT)',
    description:
      'The caudate nucleus is a C-shaped mass of striatum that forms much of the lateral wall of the lateral ventricle. It has a large head in the frontal horn, a body along the body of the ventricle, and a tapering tail that curves into the temporal lobe toward the amygdala. Together with the putamen it constitutes the striatum - the main input station of the basal ganglia.\n\nIt receives dense glutamatergic afferents from association and prefrontal cortex and dopaminergic input from substantia nigra compacta. Via direct and indirect pathways through pallidum and thalamus, caudate circuits support goal-directed action selection, cognitive flexibility, and habit learning rather than purely elementary motor execution.\n\nCaudate atrophy is characteristic of Huntington disease; infarcts or mass lesions can alter movement and behaviour (for example abulia). The head of the caudate is an important landmark beside the frontal horn on axial CT/MRI, separated from the lentiform nucleus by the anterior limb of the internal capsule. This mesh shows the left-hemisphere component.',
  },
  'Striatum_Caudate nucleus.r': {
    title: 'CAUDATE NUCLEUS (RIGHT)',
    description:
      'The caudate nucleus is a C-shaped mass of striatum that forms much of the lateral wall of the lateral ventricle. It has a large head in the frontal horn, a body along the body of the ventricle, and a tapering tail that curves into the temporal lobe toward the amygdala. Together with the putamen it constitutes the striatum - the main input station of the basal ganglia.\n\nIt receives dense glutamatergic afferents from association and prefrontal cortex and dopaminergic input from substantia nigra compacta. Via direct and indirect pathways through pallidum and thalamus, caudate circuits support goal-directed action selection, cognitive flexibility, and habit learning rather than purely elementary motor execution.\n\nCaudate atrophy is characteristic of Huntington disease; infarcts or mass lesions can alter movement and behaviour (for example abulia). The head of the caudate is an important landmark beside the frontal horn on axial CT/MRI, separated from the lentiform nucleus by the anterior limb of the internal capsule. This mesh shows the right-hemisphere component.',
  },
  'Striatum_Globus pallidus.l': {
    title: 'GLOBUS PALLIDUS (LEFT)',
    description:
      'The globus pallidus (pallidum) is the medial, paler component of the lentiform nucleus, divided into external (GPe) and internal (GPi) segments by the medial medullary lamina. It receives striatal GABAergic input and is a major processing and output station of the basal ganglia. GPi (with substantia nigra reticulata) provides inhibitory output to thalamus and brainstem, tonically suppressing unwanted movement.\n\nIn the direct pathway, striatal neurons inhibit GPi, releasing thalamic drive to cortex and facilitating selected actions. In the indirect pathway, striatal-GPe-subthalamic connections increase GPi inhibition of thalamus, suppressing competing programmes. This opponent organisation is the core of basal-ganglia motor selection.\n\nGPi is a standard deep-brain stimulation and lesioning target for dystonia and Parkinsonian motor complications. Pallidal injury can cause dystonia or hemidyskinesias. On MRI the pallidum sits medial to putamen; susceptibility effects may increase with age or mineral deposition. This mesh shows the left-hemisphere component.',
  },
  'Striatum_Globus pallidus.r': {
    title: 'GLOBUS PALLIDUS (RIGHT)',
    description:
      'The globus pallidus (pallidum) is the medial, paler component of the lentiform nucleus, divided into external (GPe) and internal (GPi) segments by the medial medullary lamina. It receives striatal GABAergic input and is a major processing and output station of the basal ganglia. GPi (with substantia nigra reticulata) provides inhibitory output to thalamus and brainstem, tonically suppressing unwanted movement.\n\nIn the direct pathway, striatal neurons inhibit GPi, releasing thalamic drive to cortex and facilitating selected actions. In the indirect pathway, striatal-GPe-subthalamic connections increase GPi inhibition of thalamus, suppressing competing programmes. This opponent organisation is the core of basal-ganglia motor selection.\n\nGPi is a standard deep-brain stimulation and lesioning target for dystonia and Parkinsonian motor complications. Pallidal injury can cause dystonia or hemidyskinesias. On MRI the pallidum sits medial to putamen; susceptibility effects may increase with age or mineral deposition. This mesh shows the right-hemisphere component.',
  },
  'Striatum_Lentiform nucleus.l': {
    title: 'LENTIFORM NUCLEUS (LEFT)',
    description:
      'The lentiform (lenticular) nucleus is the wedge-shaped basal-ganglia mass composed of putamen laterally and globus pallidus medially, resembling a biconvex lens on axial section. It lies between the internal capsule medially and the external capsule laterally, with the caudate head anteromedial across the anterior limb of the internal capsule.\n\nAs a unit, the lentiform nucleus embodies both striatal input (putamen) and pallidal output circuitry of the basal ganglia motor and cognitive loops. Blood supply includes lenticulostriate branches of the MCA (and some ACA Heubner territory for anterior portions), making it vulnerable to lacunar infarct and hypertensive haemorrhage.\n\nRecognising the lentiform nucleus is essential for reading MCA territory strokes, deep haemorrhages, and the course of the internal capsule. In this atlas it is shown as the combined putamen-pallidum assembly, complementary to the separately labelled putamen and globus pallidus parcels. This mesh shows the left-hemisphere component.',
  },
  'Striatum_Lentiform nucleus.r': {
    title: 'LENTIFORM NUCLEUS (RIGHT)',
    description:
      'The lentiform (lenticular) nucleus is the wedge-shaped basal-ganglia mass composed of putamen laterally and globus pallidus medially, resembling a biconvex lens on axial section. It lies between the internal capsule medially and the external capsule laterally, with the caudate head anteromedial across the anterior limb of the internal capsule.\n\nAs a unit, the lentiform nucleus embodies both striatal input (putamen) and pallidal output circuitry of the basal ganglia motor and cognitive loops. Blood supply includes lenticulostriate branches of the MCA (and some ACA Heubner territory for anterior portions), making it vulnerable to lacunar infarct and hypertensive haemorrhage.\n\nRecognising the lentiform nucleus is essential for reading MCA territory strokes, deep haemorrhages, and the course of the internal capsule. In this atlas it is shown as the combined putamen-pallidum assembly, complementary to the separately labelled putamen and globus pallidus parcels. This mesh shows the right-hemisphere component.',
  },
  'Striatum_Putamen.l': {
    title: 'PUTAMEN (LEFT)',
    description:
      'The putamen is the lateral, larger portion of the lentiform nucleus and, with the caudate, forms the striatum. It lies lateral to the globus pallidus and medial to the external capsule / claustrum / extreme capsule and insula. Most sensorimotor and premotor cortical projections to the striatum preferentially target the putamen.\n\nPutaminal circuits are central to selecting, scaling, and automatising voluntary movement. Dopaminergic modulation from the nigrostriatal pathway enables fluid motion; its loss in Parkinson disease produces bradykinesia and rigidity with prominent putaminal involvement on functional imaging.\n\nPutaminal haemorrhage (often hypertensive) is a classic deep ICH location, causing contralateral hemiparesis and sensory loss. Putaminal infarcts and neurodegeneration (MSA, Wilson disease) likewise impair motor control. On axial imaging the putamen is the lateral grey lens of the lentiform nucleus outside the pallidum. This mesh shows the left-hemisphere component.',
  },
  'Striatum_Putamen.r': {
    title: 'PUTAMEN (RIGHT)',
    description:
      'The putamen is the lateral, larger portion of the lentiform nucleus and, with the caudate, forms the striatum. It lies lateral to the globus pallidus and medial to the external capsule / claustrum / extreme capsule and insula. Most sensorimotor and premotor cortical projections to the striatum preferentially target the putamen.\n\nPutaminal circuits are central to selecting, scaling, and automatising voluntary movement. Dopaminergic modulation from the nigrostriatal pathway enables fluid motion; its loss in Parkinson disease produces bradykinesia and rigidity with prominent putaminal involvement on functional imaging.\n\nPutaminal haemorrhage (often hypertensive) is a classic deep ICH location, causing contralateral hemiparesis and sensory loss. Putaminal infarcts and neurodegeneration (MSA, Wilson disease) likewise impair motor control. On axial imaging the putamen is the lateral grey lens of the lentiform nucleus outside the pallidum. This mesh shows the right-hemisphere component.',
  },
  'Temporal_lobe.l': {
    title: 'TEMPORAL LOBE (LEFT)',
    description:
      'The temporal lobe sits beneath the Sylvian fissure and extends from the temporal pole back toward the occipital junction. On its superior surface lie Heschl\'s (transverse temporal) gyri - primary auditory cortex - and surrounding auditory association areas. The dominant superior temporal and nearby regions support language comprehension (Wernicke neighbourhood).\n\nThe lateral temporal convexity contributes to semantic memory and multimodal association. Medially, the hippocampus, parahippocampal gyrus, and amygdala form the mesial temporal memory and emotion system. The temporal lobe is therefore central to hearing, speech meaning, episodic memory, and affective processing.\n\nTemporal-lobe epilepsy often arises from mesial structures; infarction (especially MCA inferior division) can impair auditory and language function. Herpes encephalitis preferentially involves temporal and limbic cortex. On MRI, the temporal lobe is identified below the Sylvian fissure with a prominent temporal horn of the lateral ventricle. This mesh shows the left-hemisphere component.',
  },
  'Temporal_lobe.r': {
    title: 'TEMPORAL LOBE (RIGHT)',
    description:
      'The temporal lobe sits beneath the Sylvian fissure and extends from the temporal pole back toward the occipital junction. On its superior surface lie Heschl\'s (transverse temporal) gyri - primary auditory cortex - and surrounding auditory association areas. The dominant superior temporal and nearby regions support language comprehension (Wernicke neighbourhood).\n\nThe lateral temporal convexity contributes to semantic memory and multimodal association. Medially, the hippocampus, parahippocampal gyrus, and amygdala form the mesial temporal memory and emotion system. The temporal lobe is therefore central to hearing, speech meaning, episodic memory, and affective processing.\n\nTemporal-lobe epilepsy often arises from mesial structures; infarction (especially MCA inferior division) can impair auditory and language function. Herpes encephalitis preferentially involves temporal and limbic cortex. On MRI, the temporal lobe is identified below the Sylvian fissure with a prominent temporal horn of the lateral ventricle. This mesh shows the right-hemisphere component.',
  },
  'Ventricles_WhiteMatter_Lateral ventricle.l': {
    title: 'LATERAL VENTRICLE (LEFT)',
    description:
      'The lateral ventricles are the large paired CSF spaces within each cerebral hemisphere. Each has a frontal (anterior) horn in the frontal lobe, a body under the corpus callosum, an atrium (trigone), an occipital (posterior) horn, and a temporal (inferior) horn in the temporal lobe. The caudate nucleus forms much of the lateral wall of the body and frontal horn; the hippocampus floors the temporal horn.\n\nThey communicate with the third ventricle via the foramina of Monro. CSF produced by choroid plexus circulates through these cavities; enlargement indicates hydrocephalus or atrophy-related ex vacuo change, which must be distinguished clinically.\n\nThe lateral ventricles are essential surgical and imaging landmarks for EVD placement, endoscopy, and assessing mass effect (midline shift, effacement). In this atlas the ventricular meshes help relate deep nuclei and white matter to the CSF core of each hemisphere. This mesh shows the left-hemisphere component.',
  },
  'Ventricles_WhiteMatter_Lateral ventricle.r': {
    title: 'LATERAL VENTRICLE (RIGHT)',
    description:
      'The lateral ventricles are the large paired CSF spaces within each cerebral hemisphere. Each has a frontal (anterior) horn in the frontal lobe, a body under the corpus callosum, an atrium (trigone), an occipital (posterior) horn, and a temporal (inferior) horn in the temporal lobe. The caudate nucleus forms much of the lateral wall of the body and frontal horn; the hippocampus floors the temporal horn.\n\nThey communicate with the third ventricle via the foramina of Monro. CSF produced by choroid plexus circulates through these cavities; enlargement indicates hydrocephalus or atrophy-related ex vacuo change, which must be distinguished clinically.\n\nThe lateral ventricles are essential surgical and imaging landmarks for EVD placement, endoscopy, and assessing mass effect (midline shift, effacement). In this atlas the ventricular meshes help relate deep nuclei and white matter to the CSF core of each hemisphere. This mesh shows the right-hemisphere component.',
  },
  'Ventricles_WhiteMatter_Septum pellucidum': {
    title: 'SEPTUM PELLUCIDUM',
    description:
      'The septum pellucidum is a thin, paired membranous sheet stretched between the corpus callosum above and the fornix below, separating the frontal horns of the lateral ventricles in the midline. It contains a potential cleft (cavum septum pellucidum); a persistent cavum is a common anatomical variant, especially when extending posteriorly as cavum vergae.\n\nAlthough not a primary computational centre, the septum pellucidum is an important orientation landmark on coronal and axial imaging and forms part of the medial wall of the frontal horns. Absence or dysplasia of the septum may accompany developmental anomalies such as septo-optic dysplasia.\n\nNeurosurgeons encounter it when traversing the midline ventricular system. In the atlas it marks the delicate partition between the two lateral ventricles beneath the callosal body.',
  },
  'Ventricles_WhiteMatter_White matter of telencephalon.l': {
    title: 'WHITE MATTER OF TELENCEPHALON (LEFT)',
    description:
      'Telencephalic white matter comprises the vast network of myelinated axons within the cerebral hemispheres - association fibres linking cortical areas within a hemisphere, commissural fibres crossing the midline (chiefly corpus callosum), and projection fibres connecting cortex with thalamus, brainstem, and spinal cord through the corona radiata and internal capsule.\n\nThis white-matter chassis enables distributed large-scale brain networks for language, attention, memory, and motor control. Major named bundles include the superior longitudinal fasciculus, arcuate fasciculus, uncinate fasciculus, cingulum, and inferior fronto-occipital fasciculus, among others.\n\nLeukoaraiosis, demyelination, traumatic axonal injury, and many neurodegenerative diseases disrupt these pathways and produce cognitive or motor disconnection syndromes even when cortex appears relatively spared. In the atlas, the hemispheric white-matter meshes provide spatial context for how cortical and deep grey structures are wired together. This mesh shows the left-hemisphere component.',
  },
  'Ventricles_WhiteMatter_White matter of telencephalon.r': {
    title: 'WHITE MATTER OF TELENCEPHALON (RIGHT)',
    description:
      'Telencephalic white matter comprises the vast network of myelinated axons within the cerebral hemispheres - association fibres linking cortical areas within a hemisphere, commissural fibres crossing the midline (chiefly corpus callosum), and projection fibres connecting cortex with thalamus, brainstem, and spinal cord through the corona radiata and internal capsule.\n\nThis white-matter chassis enables distributed large-scale brain networks for language, attention, memory, and motor control. Major named bundles include the superior longitudinal fasciculus, arcuate fasciculus, uncinate fasciculus, cingulum, and inferior fronto-occipital fasciculus, among others.\n\nLeukoaraiosis, demyelination, traumatic axonal injury, and many neurodegenerative diseases disrupt these pathways and produce cognitive or motor disconnection syndromes even when cortex appears relatively spared. In the atlas, the hemispheric white-matter meshes provide spatial context for how cortical and deep grey structures are wired together. This mesh shows the right-hemisphere component.',
  },
  'Vestibulocochlear nerve (VIII).l': {
    title: 'VESTIBULOCOCHLEAR NERVE (VIII) (LEFT)',
    description:
      'Cranial nerve VIII, the vestibulocochlear nerve, carries special sensory information for hearing (cochlear division) and balance (vestibular division) from the inner ear to the brainstem. It enters the cranial cavity through the internal acoustic meatus with the facial nerve, then reaches the cochlear and vestibular nuclei at the pontomedullary junction.\n\nThe cochlear nerve transmits spiral-ganglion axons from the organ of Corti; the vestibular nerve carries signals from the semicircular canals, utricle, and saccule that drive vestibulo-ocular and postural reflexes. Central pathways continue to inferior colliculus and medial geniculate for hearing, and to cerebellum and extraocular motor nuclei for balance.\n\nLesions of CN VIII or the cerebellopontine angle (for example vestibular schwannoma) cause unilateral hearing loss, tinnitus, vertigo, and imbalance, sometimes with facial-nerve involvement. Testing includes audiometry, vestibular bedside exams, and MRI of the internal auditory canals. This nerve is the key cranial nerve for auditory-vestibular anatomy in this atlas. This mesh shows the left-hemisphere component.',
  },
  'Vestibulocochlear nerve (VIII).r': {
    title: 'VESTIBULOCOCHLEAR NERVE (VIII) (RIGHT)',
    description:
      'Cranial nerve VIII, the vestibulocochlear nerve, carries special sensory information for hearing (cochlear division) and balance (vestibular division) from the inner ear to the brainstem. It enters the cranial cavity through the internal acoustic meatus with the facial nerve, then reaches the cochlear and vestibular nuclei at the pontomedullary junction.\n\nThe cochlear nerve transmits spiral-ganglion axons from the organ of Corti; the vestibular nerve carries signals from the semicircular canals, utricle, and saccule that drive vestibulo-ocular and postural reflexes. Central pathways continue to inferior colliculus and medial geniculate for hearing, and to cerebellum and extraocular motor nuclei for balance.\n\nLesions of CN VIII or the cerebellopontine angle (for example vestibular schwannoma) cause unilateral hearing loss, tinnitus, vertigo, and imbalance, sometimes with facial-nerve involvement. Testing includes audiometry, vestibular bedside exams, and MRI of the internal auditory canals. This nerve is the key cranial nerve for auditory-vestibular anatomy in this atlas. This mesh shows the right-hemisphere component.',
  },
};

export default cerebralCortexStructures;

